/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SupportRouteImport } from './routes/support'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as OrganizerRouteImport } from './routes/organizer'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ArtistsRouteImport } from './routes/artists'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OrganizerIndexRouteImport } from './routes/organizer.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as OrganizerMarketingRouteImport } from './routes/organizer.marketing'
import { Route as OrganizerEventsRouteImport } from './routes/organizer.events'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as CheckoutOrderIdRouteImport } from './routes/checkout.$orderId'
import { Route as AdminMarketingRouteImport } from './routes/admin.marketing'
import { Route as OrganizerPosIndexRouteImport } from './routes/organizer.pos.index'
import { Route as OrganizerMarketingIndexRouteImport } from './routes/organizer.marketing.index'
import { Route as OrganizerEventsIndexRouteImport } from './routes/organizer.events.index'
import { Route as OrganizerPosSalesRouteImport } from './routes/organizer.pos.sales'
import { Route as OrganizerPosFiscalRouteImport } from './routes/organizer.pos.fiscal'
import { Route as OrganizerPosDevicesRouteImport } from './routes/organizer.pos.devices'
import { Route as OrganizerPosClosingRouteImport } from './routes/organizer.pos.closing'
import { Route as OrganizerPosCashiersRouteImport } from './routes/organizer.pos.cashiers'
import { Route as OrganizerPosCashierSalesRouteImport } from './routes/organizer.pos.cashier-sales'
import { Route as OrganizerMarketingNewRouteImport } from './routes/organizer.marketing.new'
import { Route as OrganizerEventsNewRouteImport } from './routes/organizer.events.new'
import { Route as CheckoutSuccessOrderIdRouteImport } from './routes/checkout.success.$orderId'
import { Route as ApiPublicSeedDemoRouteImport } from './routes/api.public.seed-demo'
import { Route as AdminSystemWalletRouteImport } from './routes/admin.system.wallet'
import { Route as AdminSystemUsersRouteImport } from './routes/admin.system.users'
import { Route as AdminSystemEmailTemplatesRouteImport } from './routes/admin.system.email-templates'
import { Route as AdminSalesSalesRouteImport } from './routes/admin.sales.sales'
import { Route as AdminSalesNotesRouteImport } from './routes/admin.sales.notes'
import { Route as AdminSalesCancellationsRouteImport } from './routes/admin.sales.cancellations'
import { Route as AdminReportsSalesRouteImport } from './routes/admin.reports.sales'
import { Route as AdminReportsAvfRouteImport } from './routes/admin.reports.avf'
import { Route as AdminPosTerminalsRouteImport } from './routes/admin.pos.terminals'
import { Route as AdminPosSalesRouteImport } from './routes/admin.pos.sales'
import { Route as AdminPosFiscalRouteImport } from './routes/admin.pos.fiscal'
import { Route as AdminPosClosingsRouteImport } from './routes/admin.pos.closings'
import { Route as AdminPosCashiersRouteImport } from './routes/admin.pos.cashiers'
import { Route as AdminMaxiticketTicketsRouteImport } from './routes/admin.maxiticket.tickets'
import { Route as AdminMaxiticketRefundTypesRouteImport } from './routes/admin.maxiticket.refund-types'
import { Route as AdminMaxiticketProtocolsRouteImport } from './routes/admin.maxiticket.protocols'
import { Route as AdminMaxiticketPaymentsRouteImport } from './routes/admin.maxiticket.payments'
import { Route as AdminMaxiticketOrganizersRouteImport } from './routes/admin.maxiticket.organizers'
import { Route as AdminMaxiticketDevicesRouteImport } from './routes/admin.maxiticket.devices'
import { Route as AdminMaxiticketCostsRouteImport } from './routes/admin.maxiticket.costs'
import { Route as AdminMaxiticketControlRouteImport } from './routes/admin.maxiticket.control'
import { Route as AdminMaxiticketBillingRouteImport } from './routes/admin.maxiticket.billing'
import { Route as AdminMaxiticketBalancesRouteImport } from './routes/admin.maxiticket.balances'
import { Route as AdminMaxiticketAccountingReportRouteImport } from './routes/admin.maxiticket.accounting-report'
import { Route as AdminMaxiticketAccountingChecksRouteImport } from './routes/admin.maxiticket.accounting-checks'
import { Route as AdminMaxiticketAccountingBankRouteImport } from './routes/admin.maxiticket.accounting-bank'
import { Route as AdminFinanceStatsRouteImport } from './routes/admin.finance.stats'
import { Route as AdminFinancePaymentsRouteImport } from './routes/admin.finance.payments'
import { Route as AdminEventsVenuesRouteImport } from './routes/admin.events.venues'
import { Route as AdminEventsVenueLayoutsRouteImport } from './routes/admin.events.venue-layouts'
import { Route as AdminEventsEventsRouteImport } from './routes/admin.events.events'
import { Route as AdminEventsDatesRouteImport } from './routes/admin.events.dates'
import { Route as AdminEventsCouponsRouteImport } from './routes/admin.events.coupons'
import { Route as AdminDataSidesRouteImport } from './routes/admin.data.sides'
import { Route as AdminDataSectorsRouteImport } from './routes/admin.data.sectors'
import { Route as AdminDataRowsRouteImport } from './routes/admin.data.rows'
import { Route as AdminDataPriceCategoriesRouteImport } from './routes/admin.data.price-categories'
import { Route as AdminDataPerformersRouteImport } from './routes/admin.data.performers'
import { Route as AdminDataGroupsRouteImport } from './routes/admin.data.groups'
import { Route as AdminDataDiscountsRouteImport } from './routes/admin.data.discounts'
import { Route as AdminDataDiscountCategoriesRouteImport } from './routes/admin.data.discount-categories'
import { Route as AdminDataContentRouteImport } from './routes/admin.data.content'
import { Route as AdminDataCategoriesRouteImport } from './routes/admin.data.categories'
import { Route as ApiPublicTicketsStatsRouteImport } from './routes/api.public.tickets.stats'
import { Route as ApiPublicTicketsScanRouteImport } from './routes/api.public.tickets.scan'
import { Route as ApiPublicEventsByTokenRouteImport } from './routes/api.public.events.by-token'
import { Route as ApiPublicPaymentsGopayWebhookRouteImport } from './routes/api.public.payments.gopay.webhook'
import { Route as AdminDataCategoriesCategoryIdEventsNewRouteImport } from './routes/admin.data.categories.$categoryId.events.new'

const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerRoute = OrganizerRouteImport.update({
  id: '/organizer',
  path: '/organizer',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsRoute = ArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerIndexRoute = OrganizerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrganizerRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const OrganizerMarketingRoute = OrganizerMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => OrganizerRoute,
} as any)
const OrganizerEventsRoute = OrganizerEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => OrganizerRoute,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EventsRoute,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutOrderIdRoute = CheckoutOrderIdRouteImport.update({
  id: '/checkout/$orderId',
  path: '/checkout/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMarketingRoute = AdminMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AdminRoute,
} as any)
const OrganizerPosIndexRoute = OrganizerPosIndexRouteImport.update({
  id: '/pos/',
  path: '/pos/',
  getParentRoute: () => OrganizerRoute,
} as any)
const OrganizerMarketingIndexRoute = OrganizerMarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrganizerMarketingRoute,
} as any)
const OrganizerEventsIndexRoute = OrganizerEventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrganizerEventsRoute,
} as any)
const OrganizerPosSalesRoute = OrganizerPosSalesRouteImport.update({
  id: '/pos/sales',
  path: '/pos/sales',
  getParentRoute: () => OrganizerRoute,
} as any)
const OrganizerPosFiscalRoute = OrganizerPosFiscalRouteImport.update({
  id: '/pos/fiscal',
  path: '/pos/fiscal',
  getParentRoute: () => OrganizerRoute,
} as any)
const OrganizerPosDevicesRoute = OrganizerPosDevicesRouteImport.update({
  id: '/pos/devices',
  path: '/pos/devices',
  getParentRoute: () => OrganizerRoute,
} as any)
const OrganizerPosClosingRoute = OrganizerPosClosingRouteImport.update({
  id: '/pos/closing',
  path: '/pos/closing',
  getParentRoute: () => OrganizerRoute,
} as any)
const OrganizerPosCashiersRoute = OrganizerPosCashiersRouteImport.update({
  id: '/pos/cashiers',
  path: '/pos/cashiers',
  getParentRoute: () => OrganizerRoute,
} as any)
const OrganizerPosCashierSalesRoute =
  OrganizerPosCashierSalesRouteImport.update({
    id: '/pos/cashier-sales',
    path: '/pos/cashier-sales',
    getParentRoute: () => OrganizerRoute,
  } as any)
const OrganizerMarketingNewRoute = OrganizerMarketingNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => OrganizerMarketingRoute,
} as any)
const OrganizerEventsNewRoute = OrganizerEventsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => OrganizerEventsRoute,
} as any)
const CheckoutSuccessOrderIdRoute = CheckoutSuccessOrderIdRouteImport.update({
  id: '/checkout/success/$orderId',
  path: '/checkout/success/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSeedDemoRoute = ApiPublicSeedDemoRouteImport.update({
  id: '/api/public/seed-demo',
  path: '/api/public/seed-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSystemWalletRoute = AdminSystemWalletRouteImport.update({
  id: '/system/wallet',
  path: '/system/wallet',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemUsersRoute = AdminSystemUsersRouteImport.update({
  id: '/system/users',
  path: '/system/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemEmailTemplatesRoute =
  AdminSystemEmailTemplatesRouteImport.update({
    id: '/system/email-templates',
    path: '/system/email-templates',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminSalesSalesRoute = AdminSalesSalesRouteImport.update({
  id: '/sales/sales',
  path: '/sales/sales',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSalesNotesRoute = AdminSalesNotesRouteImport.update({
  id: '/sales/notes',
  path: '/sales/notes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSalesCancellationsRoute = AdminSalesCancellationsRouteImport.update({
  id: '/sales/cancellations',
  path: '/sales/cancellations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsSalesRoute = AdminReportsSalesRouteImport.update({
  id: '/reports/sales',
  path: '/reports/sales',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsAvfRoute = AdminReportsAvfRouteImport.update({
  id: '/reports/avf',
  path: '/reports/avf',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPosTerminalsRoute = AdminPosTerminalsRouteImport.update({
  id: '/pos/terminals',
  path: '/pos/terminals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPosSalesRoute = AdminPosSalesRouteImport.update({
  id: '/pos/sales',
  path: '/pos/sales',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPosFiscalRoute = AdminPosFiscalRouteImport.update({
  id: '/pos/fiscal',
  path: '/pos/fiscal',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPosClosingsRoute = AdminPosClosingsRouteImport.update({
  id: '/pos/closings',
  path: '/pos/closings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPosCashiersRoute = AdminPosCashiersRouteImport.update({
  id: '/pos/cashiers',
  path: '/pos/cashiers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMaxiticketTicketsRoute = AdminMaxiticketTicketsRouteImport.update({
  id: '/maxiticket/tickets',
  path: '/maxiticket/tickets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMaxiticketRefundTypesRoute =
  AdminMaxiticketRefundTypesRouteImport.update({
    id: '/maxiticket/refund-types',
    path: '/maxiticket/refund-types',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminMaxiticketProtocolsRoute =
  AdminMaxiticketProtocolsRouteImport.update({
    id: '/maxiticket/protocols',
    path: '/maxiticket/protocols',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminMaxiticketPaymentsRoute = AdminMaxiticketPaymentsRouteImport.update({
  id: '/maxiticket/payments',
  path: '/maxiticket/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMaxiticketOrganizersRoute =
  AdminMaxiticketOrganizersRouteImport.update({
    id: '/maxiticket/organizers',
    path: '/maxiticket/organizers',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminMaxiticketDevicesRoute = AdminMaxiticketDevicesRouteImport.update({
  id: '/maxiticket/devices',
  path: '/maxiticket/devices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMaxiticketCostsRoute = AdminMaxiticketCostsRouteImport.update({
  id: '/maxiticket/costs',
  path: '/maxiticket/costs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMaxiticketControlRoute = AdminMaxiticketControlRouteImport.update({
  id: '/maxiticket/control',
  path: '/maxiticket/control',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMaxiticketBillingRoute = AdminMaxiticketBillingRouteImport.update({
  id: '/maxiticket/billing',
  path: '/maxiticket/billing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMaxiticketBalancesRoute = AdminMaxiticketBalancesRouteImport.update({
  id: '/maxiticket/balances',
  path: '/maxiticket/balances',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMaxiticketAccountingReportRoute =
  AdminMaxiticketAccountingReportRouteImport.update({
    id: '/maxiticket/accounting-report',
    path: '/maxiticket/accounting-report',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminMaxiticketAccountingChecksRoute =
  AdminMaxiticketAccountingChecksRouteImport.update({
    id: '/maxiticket/accounting-checks',
    path: '/maxiticket/accounting-checks',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminMaxiticketAccountingBankRoute =
  AdminMaxiticketAccountingBankRouteImport.update({
    id: '/maxiticket/accounting-bank',
    path: '/maxiticket/accounting-bank',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminFinanceStatsRoute = AdminFinanceStatsRouteImport.update({
  id: '/finance/stats',
  path: '/finance/stats',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinancePaymentsRoute = AdminFinancePaymentsRouteImport.update({
  id: '/finance/payments',
  path: '/finance/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsVenuesRoute = AdminEventsVenuesRouteImport.update({
  id: '/events/venues',
  path: '/events/venues',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsVenueLayoutsRoute = AdminEventsVenueLayoutsRouteImport.update({
  id: '/events/venue-layouts',
  path: '/events/venue-layouts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsEventsRoute = AdminEventsEventsRouteImport.update({
  id: '/events/events',
  path: '/events/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsDatesRoute = AdminEventsDatesRouteImport.update({
  id: '/events/dates',
  path: '/events/dates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsCouponsRoute = AdminEventsCouponsRouteImport.update({
  id: '/events/coupons',
  path: '/events/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDataSidesRoute = AdminDataSidesRouteImport.update({
  id: '/data/sides',
  path: '/data/sides',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDataSectorsRoute = AdminDataSectorsRouteImport.update({
  id: '/data/sectors',
  path: '/data/sectors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDataRowsRoute = AdminDataRowsRouteImport.update({
  id: '/data/rows',
  path: '/data/rows',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDataPriceCategoriesRoute =
  AdminDataPriceCategoriesRouteImport.update({
    id: '/data/price-categories',
    path: '/data/price-categories',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminDataPerformersRoute = AdminDataPerformersRouteImport.update({
  id: '/data/performers',
  path: '/data/performers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDataGroupsRoute = AdminDataGroupsRouteImport.update({
  id: '/data/groups',
  path: '/data/groups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDataDiscountsRoute = AdminDataDiscountsRouteImport.update({
  id: '/data/discounts',
  path: '/data/discounts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDataDiscountCategoriesRoute =
  AdminDataDiscountCategoriesRouteImport.update({
    id: '/data/discount-categories',
    path: '/data/discount-categories',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminDataContentRoute = AdminDataContentRouteImport.update({
  id: '/data/content',
  path: '/data/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDataCategoriesRoute = AdminDataCategoriesRouteImport.update({
  id: '/data/categories',
  path: '/data/categories',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicTicketsStatsRoute = ApiPublicTicketsStatsRouteImport.update({
  id: '/api/public/tickets/stats',
  path: '/api/public/tickets/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTicketsScanRoute = ApiPublicTicketsScanRouteImport.update({
  id: '/api/public/tickets/scan',
  path: '/api/public/tickets/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEventsByTokenRoute = ApiPublicEventsByTokenRouteImport.update({
  id: '/api/public/events/by-token',
  path: '/api/public/events/by-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsGopayWebhookRoute =
  ApiPublicPaymentsGopayWebhookRouteImport.update({
    id: '/api/public/payments/gopay/webhook',
    path: '/api/public/payments/gopay/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDataCategoriesCategoryIdEventsNewRoute =
  AdminDataCategoriesCategoryIdEventsNewRouteImport.update({
    id: '/$categoryId/events/new',
    path: '/$categoryId/events/new',
    getParentRoute: () => AdminDataCategoriesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/artists': typeof ArtistsRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/organizer': typeof OrganizerRouteWithChildren
  '/partners': typeof PartnersRoute
  '/register': typeof RegisterRoute
  '/scanner': typeof ScannerRoute
  '/support': typeof SupportRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/checkout/$orderId': typeof CheckoutOrderIdRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/events/$id': typeof EventsIdRoute
  '/organizer/events': typeof OrganizerEventsRouteWithChildren
  '/organizer/marketing': typeof OrganizerMarketingRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/organizer/': typeof OrganizerIndexRoute
  '/admin/data/categories': typeof AdminDataCategoriesRouteWithChildren
  '/admin/data/content': typeof AdminDataContentRoute
  '/admin/data/discount-categories': typeof AdminDataDiscountCategoriesRoute
  '/admin/data/discounts': typeof AdminDataDiscountsRoute
  '/admin/data/groups': typeof AdminDataGroupsRoute
  '/admin/data/performers': typeof AdminDataPerformersRoute
  '/admin/data/price-categories': typeof AdminDataPriceCategoriesRoute
  '/admin/data/rows': typeof AdminDataRowsRoute
  '/admin/data/sectors': typeof AdminDataSectorsRoute
  '/admin/data/sides': typeof AdminDataSidesRoute
  '/admin/events/coupons': typeof AdminEventsCouponsRoute
  '/admin/events/dates': typeof AdminEventsDatesRoute
  '/admin/events/events': typeof AdminEventsEventsRoute
  '/admin/events/venue-layouts': typeof AdminEventsVenueLayoutsRoute
  '/admin/events/venues': typeof AdminEventsVenuesRoute
  '/admin/finance/payments': typeof AdminFinancePaymentsRoute
  '/admin/finance/stats': typeof AdminFinanceStatsRoute
  '/admin/maxiticket/accounting-bank': typeof AdminMaxiticketAccountingBankRoute
  '/admin/maxiticket/accounting-checks': typeof AdminMaxiticketAccountingChecksRoute
  '/admin/maxiticket/accounting-report': typeof AdminMaxiticketAccountingReportRoute
  '/admin/maxiticket/balances': typeof AdminMaxiticketBalancesRoute
  '/admin/maxiticket/billing': typeof AdminMaxiticketBillingRoute
  '/admin/maxiticket/control': typeof AdminMaxiticketControlRoute
  '/admin/maxiticket/costs': typeof AdminMaxiticketCostsRoute
  '/admin/maxiticket/devices': typeof AdminMaxiticketDevicesRoute
  '/admin/maxiticket/organizers': typeof AdminMaxiticketOrganizersRoute
  '/admin/maxiticket/payments': typeof AdminMaxiticketPaymentsRoute
  '/admin/maxiticket/protocols': typeof AdminMaxiticketProtocolsRoute
  '/admin/maxiticket/refund-types': typeof AdminMaxiticketRefundTypesRoute
  '/admin/maxiticket/tickets': typeof AdminMaxiticketTicketsRoute
  '/admin/pos/cashiers': typeof AdminPosCashiersRoute
  '/admin/pos/closings': typeof AdminPosClosingsRoute
  '/admin/pos/fiscal': typeof AdminPosFiscalRoute
  '/admin/pos/sales': typeof AdminPosSalesRoute
  '/admin/pos/terminals': typeof AdminPosTerminalsRoute
  '/admin/reports/avf': typeof AdminReportsAvfRoute
  '/admin/reports/sales': typeof AdminReportsSalesRoute
  '/admin/sales/cancellations': typeof AdminSalesCancellationsRoute
  '/admin/sales/notes': typeof AdminSalesNotesRoute
  '/admin/sales/sales': typeof AdminSalesSalesRoute
  '/admin/system/email-templates': typeof AdminSystemEmailTemplatesRoute
  '/admin/system/users': typeof AdminSystemUsersRoute
  '/admin/system/wallet': typeof AdminSystemWalletRoute
  '/api/public/seed-demo': typeof ApiPublicSeedDemoRoute
  '/checkout/success/$orderId': typeof CheckoutSuccessOrderIdRoute
  '/organizer/events/new': typeof OrganizerEventsNewRoute
  '/organizer/marketing/new': typeof OrganizerMarketingNewRoute
  '/organizer/pos/cashier-sales': typeof OrganizerPosCashierSalesRoute
  '/organizer/pos/cashiers': typeof OrganizerPosCashiersRoute
  '/organizer/pos/closing': typeof OrganizerPosClosingRoute
  '/organizer/pos/devices': typeof OrganizerPosDevicesRoute
  '/organizer/pos/fiscal': typeof OrganizerPosFiscalRoute
  '/organizer/pos/sales': typeof OrganizerPosSalesRoute
  '/organizer/events/': typeof OrganizerEventsIndexRoute
  '/organizer/marketing/': typeof OrganizerMarketingIndexRoute
  '/organizer/pos/': typeof OrganizerPosIndexRoute
  '/api/public/events/by-token': typeof ApiPublicEventsByTokenRoute
  '/api/public/tickets/scan': typeof ApiPublicTicketsScanRoute
  '/api/public/tickets/stats': typeof ApiPublicTicketsStatsRoute
  '/api/public/payments/gopay/webhook': typeof ApiPublicPaymentsGopayWebhookRoute
  '/admin/data/categories/$categoryId/events/new': typeof AdminDataCategoriesCategoryIdEventsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/artists': typeof ArtistsRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/partners': typeof PartnersRoute
  '/register': typeof RegisterRoute
  '/scanner': typeof ScannerRoute
  '/support': typeof SupportRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/checkout/$orderId': typeof CheckoutOrderIdRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/events/$id': typeof EventsIdRoute
  '/admin': typeof AdminIndexRoute
  '/organizer': typeof OrganizerIndexRoute
  '/admin/data/categories': typeof AdminDataCategoriesRouteWithChildren
  '/admin/data/content': typeof AdminDataContentRoute
  '/admin/data/discount-categories': typeof AdminDataDiscountCategoriesRoute
  '/admin/data/discounts': typeof AdminDataDiscountsRoute
  '/admin/data/groups': typeof AdminDataGroupsRoute
  '/admin/data/performers': typeof AdminDataPerformersRoute
  '/admin/data/price-categories': typeof AdminDataPriceCategoriesRoute
  '/admin/data/rows': typeof AdminDataRowsRoute
  '/admin/data/sectors': typeof AdminDataSectorsRoute
  '/admin/data/sides': typeof AdminDataSidesRoute
  '/admin/events/coupons': typeof AdminEventsCouponsRoute
  '/admin/events/dates': typeof AdminEventsDatesRoute
  '/admin/events/events': typeof AdminEventsEventsRoute
  '/admin/events/venue-layouts': typeof AdminEventsVenueLayoutsRoute
  '/admin/events/venues': typeof AdminEventsVenuesRoute
  '/admin/finance/payments': typeof AdminFinancePaymentsRoute
  '/admin/finance/stats': typeof AdminFinanceStatsRoute
  '/admin/maxiticket/accounting-bank': typeof AdminMaxiticketAccountingBankRoute
  '/admin/maxiticket/accounting-checks': typeof AdminMaxiticketAccountingChecksRoute
  '/admin/maxiticket/accounting-report': typeof AdminMaxiticketAccountingReportRoute
  '/admin/maxiticket/balances': typeof AdminMaxiticketBalancesRoute
  '/admin/maxiticket/billing': typeof AdminMaxiticketBillingRoute
  '/admin/maxiticket/control': typeof AdminMaxiticketControlRoute
  '/admin/maxiticket/costs': typeof AdminMaxiticketCostsRoute
  '/admin/maxiticket/devices': typeof AdminMaxiticketDevicesRoute
  '/admin/maxiticket/organizers': typeof AdminMaxiticketOrganizersRoute
  '/admin/maxiticket/payments': typeof AdminMaxiticketPaymentsRoute
  '/admin/maxiticket/protocols': typeof AdminMaxiticketProtocolsRoute
  '/admin/maxiticket/refund-types': typeof AdminMaxiticketRefundTypesRoute
  '/admin/maxiticket/tickets': typeof AdminMaxiticketTicketsRoute
  '/admin/pos/cashiers': typeof AdminPosCashiersRoute
  '/admin/pos/closings': typeof AdminPosClosingsRoute
  '/admin/pos/fiscal': typeof AdminPosFiscalRoute
  '/admin/pos/sales': typeof AdminPosSalesRoute
  '/admin/pos/terminals': typeof AdminPosTerminalsRoute
  '/admin/reports/avf': typeof AdminReportsAvfRoute
  '/admin/reports/sales': typeof AdminReportsSalesRoute
  '/admin/sales/cancellations': typeof AdminSalesCancellationsRoute
  '/admin/sales/notes': typeof AdminSalesNotesRoute
  '/admin/sales/sales': typeof AdminSalesSalesRoute
  '/admin/system/email-templates': typeof AdminSystemEmailTemplatesRoute
  '/admin/system/users': typeof AdminSystemUsersRoute
  '/admin/system/wallet': typeof AdminSystemWalletRoute
  '/api/public/seed-demo': typeof ApiPublicSeedDemoRoute
  '/checkout/success/$orderId': typeof CheckoutSuccessOrderIdRoute
  '/organizer/events/new': typeof OrganizerEventsNewRoute
  '/organizer/marketing/new': typeof OrganizerMarketingNewRoute
  '/organizer/pos/cashier-sales': typeof OrganizerPosCashierSalesRoute
  '/organizer/pos/cashiers': typeof OrganizerPosCashiersRoute
  '/organizer/pos/closing': typeof OrganizerPosClosingRoute
  '/organizer/pos/devices': typeof OrganizerPosDevicesRoute
  '/organizer/pos/fiscal': typeof OrganizerPosFiscalRoute
  '/organizer/pos/sales': typeof OrganizerPosSalesRoute
  '/organizer/events': typeof OrganizerEventsIndexRoute
  '/organizer/marketing': typeof OrganizerMarketingIndexRoute
  '/organizer/pos': typeof OrganizerPosIndexRoute
  '/api/public/events/by-token': typeof ApiPublicEventsByTokenRoute
  '/api/public/tickets/scan': typeof ApiPublicTicketsScanRoute
  '/api/public/tickets/stats': typeof ApiPublicTicketsStatsRoute
  '/api/public/payments/gopay/webhook': typeof ApiPublicPaymentsGopayWebhookRoute
  '/admin/data/categories/$categoryId/events/new': typeof AdminDataCategoriesCategoryIdEventsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/artists': typeof ArtistsRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/organizer': typeof OrganizerRouteWithChildren
  '/partners': typeof PartnersRoute
  '/register': typeof RegisterRoute
  '/scanner': typeof ScannerRoute
  '/support': typeof SupportRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/checkout/$orderId': typeof CheckoutOrderIdRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/events/$id': typeof EventsIdRoute
  '/organizer/events': typeof OrganizerEventsRouteWithChildren
  '/organizer/marketing': typeof OrganizerMarketingRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/organizer/': typeof OrganizerIndexRoute
  '/admin/data/categories': typeof AdminDataCategoriesRouteWithChildren
  '/admin/data/content': typeof AdminDataContentRoute
  '/admin/data/discount-categories': typeof AdminDataDiscountCategoriesRoute
  '/admin/data/discounts': typeof AdminDataDiscountsRoute
  '/admin/data/groups': typeof AdminDataGroupsRoute
  '/admin/data/performers': typeof AdminDataPerformersRoute
  '/admin/data/price-categories': typeof AdminDataPriceCategoriesRoute
  '/admin/data/rows': typeof AdminDataRowsRoute
  '/admin/data/sectors': typeof AdminDataSectorsRoute
  '/admin/data/sides': typeof AdminDataSidesRoute
  '/admin/events/coupons': typeof AdminEventsCouponsRoute
  '/admin/events/dates': typeof AdminEventsDatesRoute
  '/admin/events/events': typeof AdminEventsEventsRoute
  '/admin/events/venue-layouts': typeof AdminEventsVenueLayoutsRoute
  '/admin/events/venues': typeof AdminEventsVenuesRoute
  '/admin/finance/payments': typeof AdminFinancePaymentsRoute
  '/admin/finance/stats': typeof AdminFinanceStatsRoute
  '/admin/maxiticket/accounting-bank': typeof AdminMaxiticketAccountingBankRoute
  '/admin/maxiticket/accounting-checks': typeof AdminMaxiticketAccountingChecksRoute
  '/admin/maxiticket/accounting-report': typeof AdminMaxiticketAccountingReportRoute
  '/admin/maxiticket/balances': typeof AdminMaxiticketBalancesRoute
  '/admin/maxiticket/billing': typeof AdminMaxiticketBillingRoute
  '/admin/maxiticket/control': typeof AdminMaxiticketControlRoute
  '/admin/maxiticket/costs': typeof AdminMaxiticketCostsRoute
  '/admin/maxiticket/devices': typeof AdminMaxiticketDevicesRoute
  '/admin/maxiticket/organizers': typeof AdminMaxiticketOrganizersRoute
  '/admin/maxiticket/payments': typeof AdminMaxiticketPaymentsRoute
  '/admin/maxiticket/protocols': typeof AdminMaxiticketProtocolsRoute
  '/admin/maxiticket/refund-types': typeof AdminMaxiticketRefundTypesRoute
  '/admin/maxiticket/tickets': typeof AdminMaxiticketTicketsRoute
  '/admin/pos/cashiers': typeof AdminPosCashiersRoute
  '/admin/pos/closings': typeof AdminPosClosingsRoute
  '/admin/pos/fiscal': typeof AdminPosFiscalRoute
  '/admin/pos/sales': typeof AdminPosSalesRoute
  '/admin/pos/terminals': typeof AdminPosTerminalsRoute
  '/admin/reports/avf': typeof AdminReportsAvfRoute
  '/admin/reports/sales': typeof AdminReportsSalesRoute
  '/admin/sales/cancellations': typeof AdminSalesCancellationsRoute
  '/admin/sales/notes': typeof AdminSalesNotesRoute
  '/admin/sales/sales': typeof AdminSalesSalesRoute
  '/admin/system/email-templates': typeof AdminSystemEmailTemplatesRoute
  '/admin/system/users': typeof AdminSystemUsersRoute
  '/admin/system/wallet': typeof AdminSystemWalletRoute
  '/api/public/seed-demo': typeof ApiPublicSeedDemoRoute
  '/checkout/success/$orderId': typeof CheckoutSuccessOrderIdRoute
  '/organizer/events/new': typeof OrganizerEventsNewRoute
  '/organizer/marketing/new': typeof OrganizerMarketingNewRoute
  '/organizer/pos/cashier-sales': typeof OrganizerPosCashierSalesRoute
  '/organizer/pos/cashiers': typeof OrganizerPosCashiersRoute
  '/organizer/pos/closing': typeof OrganizerPosClosingRoute
  '/organizer/pos/devices': typeof OrganizerPosDevicesRoute
  '/organizer/pos/fiscal': typeof OrganizerPosFiscalRoute
  '/organizer/pos/sales': typeof OrganizerPosSalesRoute
  '/organizer/events/': typeof OrganizerEventsIndexRoute
  '/organizer/marketing/': typeof OrganizerMarketingIndexRoute
  '/organizer/pos/': typeof OrganizerPosIndexRoute
  '/api/public/events/by-token': typeof ApiPublicEventsByTokenRoute
  '/api/public/tickets/scan': typeof ApiPublicTicketsScanRoute
  '/api/public/tickets/stats': typeof ApiPublicTicketsStatsRoute
  '/api/public/payments/gopay/webhook': typeof ApiPublicPaymentsGopayWebhookRoute
  '/admin/data/categories/$categoryId/events/new': typeof AdminDataCategoriesCategoryIdEventsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/artists'
    | '/contact'
    | '/events'
    | '/login'
    | '/marketing'
    | '/organizer'
    | '/partners'
    | '/register'
    | '/scanner'
    | '/support'
    | '/admin/marketing'
    | '/checkout/$orderId'
    | '/checkout/return'
    | '/events/$id'
    | '/organizer/events'
    | '/organizer/marketing'
    | '/admin/'
    | '/organizer/'
    | '/admin/data/categories'
    | '/admin/data/content'
    | '/admin/data/discount-categories'
    | '/admin/data/discounts'
    | '/admin/data/groups'
    | '/admin/data/performers'
    | '/admin/data/price-categories'
    | '/admin/data/rows'
    | '/admin/data/sectors'
    | '/admin/data/sides'
    | '/admin/events/coupons'
    | '/admin/events/dates'
    | '/admin/events/events'
    | '/admin/events/venue-layouts'
    | '/admin/events/venues'
    | '/admin/finance/payments'
    | '/admin/finance/stats'
    | '/admin/maxiticket/accounting-bank'
    | '/admin/maxiticket/accounting-checks'
    | '/admin/maxiticket/accounting-report'
    | '/admin/maxiticket/balances'
    | '/admin/maxiticket/billing'
    | '/admin/maxiticket/control'
    | '/admin/maxiticket/costs'
    | '/admin/maxiticket/devices'
    | '/admin/maxiticket/organizers'
    | '/admin/maxiticket/payments'
    | '/admin/maxiticket/protocols'
    | '/admin/maxiticket/refund-types'
    | '/admin/maxiticket/tickets'
    | '/admin/pos/cashiers'
    | '/admin/pos/closings'
    | '/admin/pos/fiscal'
    | '/admin/pos/sales'
    | '/admin/pos/terminals'
    | '/admin/reports/avf'
    | '/admin/reports/sales'
    | '/admin/sales/cancellations'
    | '/admin/sales/notes'
    | '/admin/sales/sales'
    | '/admin/system/email-templates'
    | '/admin/system/users'
    | '/admin/system/wallet'
    | '/api/public/seed-demo'
    | '/checkout/success/$orderId'
    | '/organizer/events/new'
    | '/organizer/marketing/new'
    | '/organizer/pos/cashier-sales'
    | '/organizer/pos/cashiers'
    | '/organizer/pos/closing'
    | '/organizer/pos/devices'
    | '/organizer/pos/fiscal'
    | '/organizer/pos/sales'
    | '/organizer/events/'
    | '/organizer/marketing/'
    | '/organizer/pos/'
    | '/api/public/events/by-token'
    | '/api/public/tickets/scan'
    | '/api/public/tickets/stats'
    | '/api/public/payments/gopay/webhook'
    | '/admin/data/categories/$categoryId/events/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/artists'
    | '/contact'
    | '/events'
    | '/login'
    | '/marketing'
    | '/partners'
    | '/register'
    | '/scanner'
    | '/support'
    | '/admin/marketing'
    | '/checkout/$orderId'
    | '/checkout/return'
    | '/events/$id'
    | '/admin'
    | '/organizer'
    | '/admin/data/categories'
    | '/admin/data/content'
    | '/admin/data/discount-categories'
    | '/admin/data/discounts'
    | '/admin/data/groups'
    | '/admin/data/performers'
    | '/admin/data/price-categories'
    | '/admin/data/rows'
    | '/admin/data/sectors'
    | '/admin/data/sides'
    | '/admin/events/coupons'
    | '/admin/events/dates'
    | '/admin/events/events'
    | '/admin/events/venue-layouts'
    | '/admin/events/venues'
    | '/admin/finance/payments'
    | '/admin/finance/stats'
    | '/admin/maxiticket/accounting-bank'
    | '/admin/maxiticket/accounting-checks'
    | '/admin/maxiticket/accounting-report'
    | '/admin/maxiticket/balances'
    | '/admin/maxiticket/billing'
    | '/admin/maxiticket/control'
    | '/admin/maxiticket/costs'
    | '/admin/maxiticket/devices'
    | '/admin/maxiticket/organizers'
    | '/admin/maxiticket/payments'
    | '/admin/maxiticket/protocols'
    | '/admin/maxiticket/refund-types'
    | '/admin/maxiticket/tickets'
    | '/admin/pos/cashiers'
    | '/admin/pos/closings'
    | '/admin/pos/fiscal'
    | '/admin/pos/sales'
    | '/admin/pos/terminals'
    | '/admin/reports/avf'
    | '/admin/reports/sales'
    | '/admin/sales/cancellations'
    | '/admin/sales/notes'
    | '/admin/sales/sales'
    | '/admin/system/email-templates'
    | '/admin/system/users'
    | '/admin/system/wallet'
    | '/api/public/seed-demo'
    | '/checkout/success/$orderId'
    | '/organizer/events/new'
    | '/organizer/marketing/new'
    | '/organizer/pos/cashier-sales'
    | '/organizer/pos/cashiers'
    | '/organizer/pos/closing'
    | '/organizer/pos/devices'
    | '/organizer/pos/fiscal'
    | '/organizer/pos/sales'
    | '/organizer/events'
    | '/organizer/marketing'
    | '/organizer/pos'
    | '/api/public/events/by-token'
    | '/api/public/tickets/scan'
    | '/api/public/tickets/stats'
    | '/api/public/payments/gopay/webhook'
    | '/admin/data/categories/$categoryId/events/new'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/artists'
    | '/contact'
    | '/events'
    | '/login'
    | '/marketing'
    | '/organizer'
    | '/partners'
    | '/register'
    | '/scanner'
    | '/support'
    | '/admin/marketing'
    | '/checkout/$orderId'
    | '/checkout/return'
    | '/events/$id'
    | '/organizer/events'
    | '/organizer/marketing'
    | '/admin/'
    | '/organizer/'
    | '/admin/data/categories'
    | '/admin/data/content'
    | '/admin/data/discount-categories'
    | '/admin/data/discounts'
    | '/admin/data/groups'
    | '/admin/data/performers'
    | '/admin/data/price-categories'
    | '/admin/data/rows'
    | '/admin/data/sectors'
    | '/admin/data/sides'
    | '/admin/events/coupons'
    | '/admin/events/dates'
    | '/admin/events/events'
    | '/admin/events/venue-layouts'
    | '/admin/events/venues'
    | '/admin/finance/payments'
    | '/admin/finance/stats'
    | '/admin/maxiticket/accounting-bank'
    | '/admin/maxiticket/accounting-checks'
    | '/admin/maxiticket/accounting-report'
    | '/admin/maxiticket/balances'
    | '/admin/maxiticket/billing'
    | '/admin/maxiticket/control'
    | '/admin/maxiticket/costs'
    | '/admin/maxiticket/devices'
    | '/admin/maxiticket/organizers'
    | '/admin/maxiticket/payments'
    | '/admin/maxiticket/protocols'
    | '/admin/maxiticket/refund-types'
    | '/admin/maxiticket/tickets'
    | '/admin/pos/cashiers'
    | '/admin/pos/closings'
    | '/admin/pos/fiscal'
    | '/admin/pos/sales'
    | '/admin/pos/terminals'
    | '/admin/reports/avf'
    | '/admin/reports/sales'
    | '/admin/sales/cancellations'
    | '/admin/sales/notes'
    | '/admin/sales/sales'
    | '/admin/system/email-templates'
    | '/admin/system/users'
    | '/admin/system/wallet'
    | '/api/public/seed-demo'
    | '/checkout/success/$orderId'
    | '/organizer/events/new'
    | '/organizer/marketing/new'
    | '/organizer/pos/cashier-sales'
    | '/organizer/pos/cashiers'
    | '/organizer/pos/closing'
    | '/organizer/pos/devices'
    | '/organizer/pos/fiscal'
    | '/organizer/pos/sales'
    | '/organizer/events/'
    | '/organizer/marketing/'
    | '/organizer/pos/'
    | '/api/public/events/by-token'
    | '/api/public/tickets/scan'
    | '/api/public/tickets/stats'
    | '/api/public/payments/gopay/webhook'
    | '/admin/data/categories/$categoryId/events/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  ArtistsRoute: typeof ArtistsRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRouteWithChildren
  LoginRoute: typeof LoginRoute
  MarketingRoute: typeof MarketingRoute
  OrganizerRoute: typeof OrganizerRouteWithChildren
  PartnersRoute: typeof PartnersRoute
  RegisterRoute: typeof RegisterRoute
  ScannerRoute: typeof ScannerRoute
  SupportRoute: typeof SupportRoute
  CheckoutOrderIdRoute: typeof CheckoutOrderIdRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ApiPublicSeedDemoRoute: typeof ApiPublicSeedDemoRoute
  CheckoutSuccessOrderIdRoute: typeof CheckoutSuccessOrderIdRoute
  ApiPublicEventsByTokenRoute: typeof ApiPublicEventsByTokenRoute
  ApiPublicTicketsScanRoute: typeof ApiPublicTicketsScanRoute
  ApiPublicTicketsStatsRoute: typeof ApiPublicTicketsStatsRoute
  ApiPublicPaymentsGopayWebhookRoute: typeof ApiPublicPaymentsGopayWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer': {
      id: '/organizer'
      path: '/organizer'
      fullPath: '/organizer'
      preLoaderRoute: typeof OrganizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists': {
      id: '/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof ArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/': {
      id: '/organizer/'
      path: '/'
      fullPath: '/organizer/'
      preLoaderRoute: typeof OrganizerIndexRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/organizer/marketing': {
      id: '/organizer/marketing'
      path: '/marketing'
      fullPath: '/organizer/marketing'
      preLoaderRoute: typeof OrganizerMarketingRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/organizer/events': {
      id: '/organizer/events'
      path: '/events'
      fullPath: '/organizer/events'
      preLoaderRoute: typeof OrganizerEventsRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$orderId': {
      id: '/checkout/$orderId'
      path: '/checkout/$orderId'
      fullPath: '/checkout/$orderId'
      preLoaderRoute: typeof CheckoutOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/marketing': {
      id: '/admin/marketing'
      path: '/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AdminMarketingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/organizer/pos/': {
      id: '/organizer/pos/'
      path: '/pos'
      fullPath: '/organizer/pos/'
      preLoaderRoute: typeof OrganizerPosIndexRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/organizer/marketing/': {
      id: '/organizer/marketing/'
      path: '/'
      fullPath: '/organizer/marketing/'
      preLoaderRoute: typeof OrganizerMarketingIndexRouteImport
      parentRoute: typeof OrganizerMarketingRoute
    }
    '/organizer/events/': {
      id: '/organizer/events/'
      path: '/'
      fullPath: '/organizer/events/'
      preLoaderRoute: typeof OrganizerEventsIndexRouteImport
      parentRoute: typeof OrganizerEventsRoute
    }
    '/organizer/pos/sales': {
      id: '/organizer/pos/sales'
      path: '/pos/sales'
      fullPath: '/organizer/pos/sales'
      preLoaderRoute: typeof OrganizerPosSalesRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/organizer/pos/fiscal': {
      id: '/organizer/pos/fiscal'
      path: '/pos/fiscal'
      fullPath: '/organizer/pos/fiscal'
      preLoaderRoute: typeof OrganizerPosFiscalRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/organizer/pos/devices': {
      id: '/organizer/pos/devices'
      path: '/pos/devices'
      fullPath: '/organizer/pos/devices'
      preLoaderRoute: typeof OrganizerPosDevicesRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/organizer/pos/closing': {
      id: '/organizer/pos/closing'
      path: '/pos/closing'
      fullPath: '/organizer/pos/closing'
      preLoaderRoute: typeof OrganizerPosClosingRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/organizer/pos/cashiers': {
      id: '/organizer/pos/cashiers'
      path: '/pos/cashiers'
      fullPath: '/organizer/pos/cashiers'
      preLoaderRoute: typeof OrganizerPosCashiersRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/organizer/pos/cashier-sales': {
      id: '/organizer/pos/cashier-sales'
      path: '/pos/cashier-sales'
      fullPath: '/organizer/pos/cashier-sales'
      preLoaderRoute: typeof OrganizerPosCashierSalesRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/organizer/marketing/new': {
      id: '/organizer/marketing/new'
      path: '/new'
      fullPath: '/organizer/marketing/new'
      preLoaderRoute: typeof OrganizerMarketingNewRouteImport
      parentRoute: typeof OrganizerMarketingRoute
    }
    '/organizer/events/new': {
      id: '/organizer/events/new'
      path: '/new'
      fullPath: '/organizer/events/new'
      preLoaderRoute: typeof OrganizerEventsNewRouteImport
      parentRoute: typeof OrganizerEventsRoute
    }
    '/checkout/success/$orderId': {
      id: '/checkout/success/$orderId'
      path: '/checkout/success/$orderId'
      fullPath: '/checkout/success/$orderId'
      preLoaderRoute: typeof CheckoutSuccessOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/seed-demo': {
      id: '/api/public/seed-demo'
      path: '/api/public/seed-demo'
      fullPath: '/api/public/seed-demo'
      preLoaderRoute: typeof ApiPublicSeedDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/system/wallet': {
      id: '/admin/system/wallet'
      path: '/system/wallet'
      fullPath: '/admin/system/wallet'
      preLoaderRoute: typeof AdminSystemWalletRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system/users': {
      id: '/admin/system/users'
      path: '/system/users'
      fullPath: '/admin/system/users'
      preLoaderRoute: typeof AdminSystemUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system/email-templates': {
      id: '/admin/system/email-templates'
      path: '/system/email-templates'
      fullPath: '/admin/system/email-templates'
      preLoaderRoute: typeof AdminSystemEmailTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sales/sales': {
      id: '/admin/sales/sales'
      path: '/sales/sales'
      fullPath: '/admin/sales/sales'
      preLoaderRoute: typeof AdminSalesSalesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sales/notes': {
      id: '/admin/sales/notes'
      path: '/sales/notes'
      fullPath: '/admin/sales/notes'
      preLoaderRoute: typeof AdminSalesNotesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sales/cancellations': {
      id: '/admin/sales/cancellations'
      path: '/sales/cancellations'
      fullPath: '/admin/sales/cancellations'
      preLoaderRoute: typeof AdminSalesCancellationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports/sales': {
      id: '/admin/reports/sales'
      path: '/reports/sales'
      fullPath: '/admin/reports/sales'
      preLoaderRoute: typeof AdminReportsSalesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports/avf': {
      id: '/admin/reports/avf'
      path: '/reports/avf'
      fullPath: '/admin/reports/avf'
      preLoaderRoute: typeof AdminReportsAvfRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pos/terminals': {
      id: '/admin/pos/terminals'
      path: '/pos/terminals'
      fullPath: '/admin/pos/terminals'
      preLoaderRoute: typeof AdminPosTerminalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pos/sales': {
      id: '/admin/pos/sales'
      path: '/pos/sales'
      fullPath: '/admin/pos/sales'
      preLoaderRoute: typeof AdminPosSalesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pos/fiscal': {
      id: '/admin/pos/fiscal'
      path: '/pos/fiscal'
      fullPath: '/admin/pos/fiscal'
      preLoaderRoute: typeof AdminPosFiscalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pos/closings': {
      id: '/admin/pos/closings'
      path: '/pos/closings'
      fullPath: '/admin/pos/closings'
      preLoaderRoute: typeof AdminPosClosingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pos/cashiers': {
      id: '/admin/pos/cashiers'
      path: '/pos/cashiers'
      fullPath: '/admin/pos/cashiers'
      preLoaderRoute: typeof AdminPosCashiersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/maxiticket/tickets': {
      id: '/admin/maxiticket/tickets'
      path: '/maxiticket/tickets'
      fullPath: '/admin/maxiticket/tickets'
      preLoaderRoute: typeof AdminMaxiticketTicketsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/maxiticket/refund-types': {
      id: '/admin/maxiticket/refund-types'
      path: '/maxiticket/refund-types'
      fullPath: '/admin/maxiticket/refund-types'
      preLoaderRoute: typeof AdminMaxiticketRefundTypesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/maxiticket/protocols': {
      id: '/admin/maxiticket/protocols'
      path: '/maxiticket/protocols'
      fullPath: '/admin/maxiticket/protocols'
      preLoaderRoute: typeof AdminMaxiticketProtocolsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/maxiticket/payments': {
      id: '/admin/maxiticket/payments'
      path: '/maxiticket/payments'
      fullPath: '/admin/maxiticket/payments'
      preLoaderRoute: typeof AdminMaxiticketPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/maxiticket/organizers': {
      id: '/admin/maxiticket/organizers'
      path: '/maxiticket/organizers'
      fullPath: '/admin/maxiticket/organizers'
      preLoaderRoute: typeof AdminMaxiticketOrganizersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/maxiticket/devices': {
      id: '/admin/maxiticket/devices'
      path: '/maxiticket/devices'
      fullPath: '/admin/maxiticket/devices'
      preLoaderRoute: typeof AdminMaxiticketDevicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/maxiticket/costs': {
      id: '/admin/maxiticket/costs'
      path: '/maxiticket/costs'
      fullPath: '/admin/maxiticket/costs'
      preLoaderRoute: typeof AdminMaxiticketCostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/maxiticket/control': {
      id: '/admin/maxiticket/control'
      path: '/maxiticket/control'
      fullPath: '/admin/maxiticket/control'
      preLoaderRoute: typeof AdminMaxiticketControlRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/maxiticket/billing': {
      id: '/admin/maxiticket/billing'
      path: '/maxiticket/billing'
      fullPath: '/admin/maxiticket/billing'
      preLoaderRoute: typeof AdminMaxiticketBillingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/maxiticket/balances': {
      id: '/admin/maxiticket/balances'
      path: '/maxiticket/balances'
      fullPath: '/admin/maxiticket/balances'
      preLoaderRoute: typeof AdminMaxiticketBalancesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/maxiticket/accounting-report': {
      id: '/admin/maxiticket/accounting-report'
      path: '/maxiticket/accounting-report'
      fullPath: '/admin/maxiticket/accounting-report'
      preLoaderRoute: typeof AdminMaxiticketAccountingReportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/maxiticket/accounting-checks': {
      id: '/admin/maxiticket/accounting-checks'
      path: '/maxiticket/accounting-checks'
      fullPath: '/admin/maxiticket/accounting-checks'
      preLoaderRoute: typeof AdminMaxiticketAccountingChecksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/maxiticket/accounting-bank': {
      id: '/admin/maxiticket/accounting-bank'
      path: '/maxiticket/accounting-bank'
      fullPath: '/admin/maxiticket/accounting-bank'
      preLoaderRoute: typeof AdminMaxiticketAccountingBankRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance/stats': {
      id: '/admin/finance/stats'
      path: '/finance/stats'
      fullPath: '/admin/finance/stats'
      preLoaderRoute: typeof AdminFinanceStatsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance/payments': {
      id: '/admin/finance/payments'
      path: '/finance/payments'
      fullPath: '/admin/finance/payments'
      preLoaderRoute: typeof AdminFinancePaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/venues': {
      id: '/admin/events/venues'
      path: '/events/venues'
      fullPath: '/admin/events/venues'
      preLoaderRoute: typeof AdminEventsVenuesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/venue-layouts': {
      id: '/admin/events/venue-layouts'
      path: '/events/venue-layouts'
      fullPath: '/admin/events/venue-layouts'
      preLoaderRoute: typeof AdminEventsVenueLayoutsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/events': {
      id: '/admin/events/events'
      path: '/events/events'
      fullPath: '/admin/events/events'
      preLoaderRoute: typeof AdminEventsEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/dates': {
      id: '/admin/events/dates'
      path: '/events/dates'
      fullPath: '/admin/events/dates'
      preLoaderRoute: typeof AdminEventsDatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/coupons': {
      id: '/admin/events/coupons'
      path: '/events/coupons'
      fullPath: '/admin/events/coupons'
      preLoaderRoute: typeof AdminEventsCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/data/sides': {
      id: '/admin/data/sides'
      path: '/data/sides'
      fullPath: '/admin/data/sides'
      preLoaderRoute: typeof AdminDataSidesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/data/sectors': {
      id: '/admin/data/sectors'
      path: '/data/sectors'
      fullPath: '/admin/data/sectors'
      preLoaderRoute: typeof AdminDataSectorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/data/rows': {
      id: '/admin/data/rows'
      path: '/data/rows'
      fullPath: '/admin/data/rows'
      preLoaderRoute: typeof AdminDataRowsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/data/price-categories': {
      id: '/admin/data/price-categories'
      path: '/data/price-categories'
      fullPath: '/admin/data/price-categories'
      preLoaderRoute: typeof AdminDataPriceCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/data/performers': {
      id: '/admin/data/performers'
      path: '/data/performers'
      fullPath: '/admin/data/performers'
      preLoaderRoute: typeof AdminDataPerformersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/data/groups': {
      id: '/admin/data/groups'
      path: '/data/groups'
      fullPath: '/admin/data/groups'
      preLoaderRoute: typeof AdminDataGroupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/data/discounts': {
      id: '/admin/data/discounts'
      path: '/data/discounts'
      fullPath: '/admin/data/discounts'
      preLoaderRoute: typeof AdminDataDiscountsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/data/discount-categories': {
      id: '/admin/data/discount-categories'
      path: '/data/discount-categories'
      fullPath: '/admin/data/discount-categories'
      preLoaderRoute: typeof AdminDataDiscountCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/data/content': {
      id: '/admin/data/content'
      path: '/data/content'
      fullPath: '/admin/data/content'
      preLoaderRoute: typeof AdminDataContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/data/categories': {
      id: '/admin/data/categories'
      path: '/data/categories'
      fullPath: '/admin/data/categories'
      preLoaderRoute: typeof AdminDataCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/tickets/stats': {
      id: '/api/public/tickets/stats'
      path: '/api/public/tickets/stats'
      fullPath: '/api/public/tickets/stats'
      preLoaderRoute: typeof ApiPublicTicketsStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tickets/scan': {
      id: '/api/public/tickets/scan'
      path: '/api/public/tickets/scan'
      fullPath: '/api/public/tickets/scan'
      preLoaderRoute: typeof ApiPublicTicketsScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/events/by-token': {
      id: '/api/public/events/by-token'
      path: '/api/public/events/by-token'
      fullPath: '/api/public/events/by-token'
      preLoaderRoute: typeof ApiPublicEventsByTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/gopay/webhook': {
      id: '/api/public/payments/gopay/webhook'
      path: '/api/public/payments/gopay/webhook'
      fullPath: '/api/public/payments/gopay/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsGopayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/data/categories/$categoryId/events/new': {
      id: '/admin/data/categories/$categoryId/events/new'
      path: '/$categoryId/events/new'
      fullPath: '/admin/data/categories/$categoryId/events/new'
      preLoaderRoute: typeof AdminDataCategoriesCategoryIdEventsNewRouteImport
      parentRoute: typeof AdminDataCategoriesRoute
    }
  }
}

interface AdminDataCategoriesRouteChildren {
  AdminDataCategoriesCategoryIdEventsNewRoute: typeof AdminDataCategoriesCategoryIdEventsNewRoute
}

const AdminDataCategoriesRouteChildren: AdminDataCategoriesRouteChildren = {
  AdminDataCategoriesCategoryIdEventsNewRoute:
    AdminDataCategoriesCategoryIdEventsNewRoute,
}

const AdminDataCategoriesRouteWithChildren =
  AdminDataCategoriesRoute._addFileChildren(AdminDataCategoriesRouteChildren)

interface AdminRouteChildren {
  AdminMarketingRoute: typeof AdminMarketingRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminDataCategoriesRoute: typeof AdminDataCategoriesRouteWithChildren
  AdminDataContentRoute: typeof AdminDataContentRoute
  AdminDataDiscountCategoriesRoute: typeof AdminDataDiscountCategoriesRoute
  AdminDataDiscountsRoute: typeof AdminDataDiscountsRoute
  AdminDataGroupsRoute: typeof AdminDataGroupsRoute
  AdminDataPerformersRoute: typeof AdminDataPerformersRoute
  AdminDataPriceCategoriesRoute: typeof AdminDataPriceCategoriesRoute
  AdminDataRowsRoute: typeof AdminDataRowsRoute
  AdminDataSectorsRoute: typeof AdminDataSectorsRoute
  AdminDataSidesRoute: typeof AdminDataSidesRoute
  AdminEventsCouponsRoute: typeof AdminEventsCouponsRoute
  AdminEventsDatesRoute: typeof AdminEventsDatesRoute
  AdminEventsEventsRoute: typeof AdminEventsEventsRoute
  AdminEventsVenueLayoutsRoute: typeof AdminEventsVenueLayoutsRoute
  AdminEventsVenuesRoute: typeof AdminEventsVenuesRoute
  AdminFinancePaymentsRoute: typeof AdminFinancePaymentsRoute
  AdminFinanceStatsRoute: typeof AdminFinanceStatsRoute
  AdminMaxiticketAccountingBankRoute: typeof AdminMaxiticketAccountingBankRoute
  AdminMaxiticketAccountingChecksRoute: typeof AdminMaxiticketAccountingChecksRoute
  AdminMaxiticketAccountingReportRoute: typeof AdminMaxiticketAccountingReportRoute
  AdminMaxiticketBalancesRoute: typeof AdminMaxiticketBalancesRoute
  AdminMaxiticketBillingRoute: typeof AdminMaxiticketBillingRoute
  AdminMaxiticketControlRoute: typeof AdminMaxiticketControlRoute
  AdminMaxiticketCostsRoute: typeof AdminMaxiticketCostsRoute
  AdminMaxiticketDevicesRoute: typeof AdminMaxiticketDevicesRoute
  AdminMaxiticketOrganizersRoute: typeof AdminMaxiticketOrganizersRoute
  AdminMaxiticketPaymentsRoute: typeof AdminMaxiticketPaymentsRoute
  AdminMaxiticketProtocolsRoute: typeof AdminMaxiticketProtocolsRoute
  AdminMaxiticketRefundTypesRoute: typeof AdminMaxiticketRefundTypesRoute
  AdminMaxiticketTicketsRoute: typeof AdminMaxiticketTicketsRoute
  AdminPosCashiersRoute: typeof AdminPosCashiersRoute
  AdminPosClosingsRoute: typeof AdminPosClosingsRoute
  AdminPosFiscalRoute: typeof AdminPosFiscalRoute
  AdminPosSalesRoute: typeof AdminPosSalesRoute
  AdminPosTerminalsRoute: typeof AdminPosTerminalsRoute
  AdminReportsAvfRoute: typeof AdminReportsAvfRoute
  AdminReportsSalesRoute: typeof AdminReportsSalesRoute
  AdminSalesCancellationsRoute: typeof AdminSalesCancellationsRoute
  AdminSalesNotesRoute: typeof AdminSalesNotesRoute
  AdminSalesSalesRoute: typeof AdminSalesSalesRoute
  AdminSystemEmailTemplatesRoute: typeof AdminSystemEmailTemplatesRoute
  AdminSystemUsersRoute: typeof AdminSystemUsersRoute
  AdminSystemWalletRoute: typeof AdminSystemWalletRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminMarketingRoute: AdminMarketingRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminDataCategoriesRoute: AdminDataCategoriesRouteWithChildren,
  AdminDataContentRoute: AdminDataContentRoute,
  AdminDataDiscountCategoriesRoute: AdminDataDiscountCategoriesRoute,
  AdminDataDiscountsRoute: AdminDataDiscountsRoute,
  AdminDataGroupsRoute: AdminDataGroupsRoute,
  AdminDataPerformersRoute: AdminDataPerformersRoute,
  AdminDataPriceCategoriesRoute: AdminDataPriceCategoriesRoute,
  AdminDataRowsRoute: AdminDataRowsRoute,
  AdminDataSectorsRoute: AdminDataSectorsRoute,
  AdminDataSidesRoute: AdminDataSidesRoute,
  AdminEventsCouponsRoute: AdminEventsCouponsRoute,
  AdminEventsDatesRoute: AdminEventsDatesRoute,
  AdminEventsEventsRoute: AdminEventsEventsRoute,
  AdminEventsVenueLayoutsRoute: AdminEventsVenueLayoutsRoute,
  AdminEventsVenuesRoute: AdminEventsVenuesRoute,
  AdminFinancePaymentsRoute: AdminFinancePaymentsRoute,
  AdminFinanceStatsRoute: AdminFinanceStatsRoute,
  AdminMaxiticketAccountingBankRoute: AdminMaxiticketAccountingBankRoute,
  AdminMaxiticketAccountingChecksRoute: AdminMaxiticketAccountingChecksRoute,
  AdminMaxiticketAccountingReportRoute: AdminMaxiticketAccountingReportRoute,
  AdminMaxiticketBalancesRoute: AdminMaxiticketBalancesRoute,
  AdminMaxiticketBillingRoute: AdminMaxiticketBillingRoute,
  AdminMaxiticketControlRoute: AdminMaxiticketControlRoute,
  AdminMaxiticketCostsRoute: AdminMaxiticketCostsRoute,
  AdminMaxiticketDevicesRoute: AdminMaxiticketDevicesRoute,
  AdminMaxiticketOrganizersRoute: AdminMaxiticketOrganizersRoute,
  AdminMaxiticketPaymentsRoute: AdminMaxiticketPaymentsRoute,
  AdminMaxiticketProtocolsRoute: AdminMaxiticketProtocolsRoute,
  AdminMaxiticketRefundTypesRoute: AdminMaxiticketRefundTypesRoute,
  AdminMaxiticketTicketsRoute: AdminMaxiticketTicketsRoute,
  AdminPosCashiersRoute: AdminPosCashiersRoute,
  AdminPosClosingsRoute: AdminPosClosingsRoute,
  AdminPosFiscalRoute: AdminPosFiscalRoute,
  AdminPosSalesRoute: AdminPosSalesRoute,
  AdminPosTerminalsRoute: AdminPosTerminalsRoute,
  AdminReportsAvfRoute: AdminReportsAvfRoute,
  AdminReportsSalesRoute: AdminReportsSalesRoute,
  AdminSalesCancellationsRoute: AdminSalesCancellationsRoute,
  AdminSalesNotesRoute: AdminSalesNotesRoute,
  AdminSalesSalesRoute: AdminSalesSalesRoute,
  AdminSystemEmailTemplatesRoute: AdminSystemEmailTemplatesRoute,
  AdminSystemUsersRoute: AdminSystemUsersRoute,
  AdminSystemWalletRoute: AdminSystemWalletRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EventsRouteChildren {
  EventsIdRoute: typeof EventsIdRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsIdRoute: EventsIdRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface OrganizerEventsRouteChildren {
  OrganizerEventsNewRoute: typeof OrganizerEventsNewRoute
  OrganizerEventsIndexRoute: typeof OrganizerEventsIndexRoute
}

const OrganizerEventsRouteChildren: OrganizerEventsRouteChildren = {
  OrganizerEventsNewRoute: OrganizerEventsNewRoute,
  OrganizerEventsIndexRoute: OrganizerEventsIndexRoute,
}

const OrganizerEventsRouteWithChildren = OrganizerEventsRoute._addFileChildren(
  OrganizerEventsRouteChildren,
)

interface OrganizerMarketingRouteChildren {
  OrganizerMarketingNewRoute: typeof OrganizerMarketingNewRoute
  OrganizerMarketingIndexRoute: typeof OrganizerMarketingIndexRoute
}

const OrganizerMarketingRouteChildren: OrganizerMarketingRouteChildren = {
  OrganizerMarketingNewRoute: OrganizerMarketingNewRoute,
  OrganizerMarketingIndexRoute: OrganizerMarketingIndexRoute,
}

const OrganizerMarketingRouteWithChildren =
  OrganizerMarketingRoute._addFileChildren(OrganizerMarketingRouteChildren)

interface OrganizerRouteChildren {
  OrganizerEventsRoute: typeof OrganizerEventsRouteWithChildren
  OrganizerMarketingRoute: typeof OrganizerMarketingRouteWithChildren
  OrganizerIndexRoute: typeof OrganizerIndexRoute
  OrganizerPosCashierSalesRoute: typeof OrganizerPosCashierSalesRoute
  OrganizerPosCashiersRoute: typeof OrganizerPosCashiersRoute
  OrganizerPosClosingRoute: typeof OrganizerPosClosingRoute
  OrganizerPosDevicesRoute: typeof OrganizerPosDevicesRoute
  OrganizerPosFiscalRoute: typeof OrganizerPosFiscalRoute
  OrganizerPosSalesRoute: typeof OrganizerPosSalesRoute
  OrganizerPosIndexRoute: typeof OrganizerPosIndexRoute
}

const OrganizerRouteChildren: OrganizerRouteChildren = {
  OrganizerEventsRoute: OrganizerEventsRouteWithChildren,
  OrganizerMarketingRoute: OrganizerMarketingRouteWithChildren,
  OrganizerIndexRoute: OrganizerIndexRoute,
  OrganizerPosCashierSalesRoute: OrganizerPosCashierSalesRoute,
  OrganizerPosCashiersRoute: OrganizerPosCashiersRoute,
  OrganizerPosClosingRoute: OrganizerPosClosingRoute,
  OrganizerPosDevicesRoute: OrganizerPosDevicesRoute,
  OrganizerPosFiscalRoute: OrganizerPosFiscalRoute,
  OrganizerPosSalesRoute: OrganizerPosSalesRoute,
  OrganizerPosIndexRoute: OrganizerPosIndexRoute,
}

const OrganizerRouteWithChildren = OrganizerRoute._addFileChildren(
  OrganizerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  ArtistsRoute: ArtistsRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRouteWithChildren,
  LoginRoute: LoginRoute,
  MarketingRoute: MarketingRoute,
  OrganizerRoute: OrganizerRouteWithChildren,
  PartnersRoute: PartnersRoute,
  RegisterRoute: RegisterRoute,
  ScannerRoute: ScannerRoute,
  SupportRoute: SupportRoute,
  CheckoutOrderIdRoute: CheckoutOrderIdRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ApiPublicSeedDemoRoute: ApiPublicSeedDemoRoute,
  CheckoutSuccessOrderIdRoute: CheckoutSuccessOrderIdRoute,
  ApiPublicEventsByTokenRoute: ApiPublicEventsByTokenRoute,
  ApiPublicTicketsScanRoute: ApiPublicTicketsScanRoute,
  ApiPublicTicketsStatsRoute: ApiPublicTicketsStatsRoute,
  ApiPublicPaymentsGopayWebhookRoute: ApiPublicPaymentsGopayWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
