/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ArtistsRouteImport } from './routes/artists'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as EventsRouteImport } from './routes/events'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as OrganizerRouteImport } from './routes/organizer'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SupportRouteImport } from './routes/support'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminMarketingRouteImport } from './routes/admin.marketing'
import { Route as CheckoutOrderIdRouteImport } from './routes/checkout.$orderId'
import { Route as CheckoutReturnRouteImport } from './routes/checkout.return'
import { Route as EventsIdRouteImport } from './routes/events.$id'
import { Route as OrganizerIndexRouteImport } from './routes/organizer.index'
import { Route as OrganizerEventsRouteImport } from './routes/organizer.events'
import { Route as OrganizerMarketingRouteImport } from './routes/organizer.marketing'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as AdminDataCategoriesRouteImport } from './routes/admin.data.categories'
import { Route as AdminDataContentRouteImport } from './routes/admin.data.content'
import { Route as AdminDataGroupsRouteImport } from './routes/admin.data.groups'
import { Route as AdminDataPerformersRouteImport } from './routes/admin.data.performers'
import { Route as AdminDataPriceCategoriesRouteImport } from './routes/admin.data.price-categories'
import { Route as AdminEticketoAccountingBankRouteImport } from './routes/admin.eticketo.accounting-bank'
import { Route as AdminEticketoAccountingChecksRouteImport } from './routes/admin.eticketo.accounting-checks'
import { Route as AdminEticketoAccountingReportRouteImport } from './routes/admin.eticketo.accounting-report'
import { Route as AdminEticketoBalancesRouteImport } from './routes/admin.eticketo.balances'
import { Route as AdminEticketoBillingRouteImport } from './routes/admin.eticketo.billing'
import { Route as AdminEticketoControlRouteImport } from './routes/admin.eticketo.control'
import { Route as AdminEticketoCostsRouteImport } from './routes/admin.eticketo.costs'
import { Route as AdminEticketoDevicesRouteImport } from './routes/admin.eticketo.devices'
import { Route as AdminEticketoOrganizersRouteImport } from './routes/admin.eticketo.organizers'
import { Route as AdminEticketoPaymentsRouteImport } from './routes/admin.eticketo.payments'
import { Route as AdminEticketoProtocolsRouteImport } from './routes/admin.eticketo.protocols'
import { Route as AdminEticketoRefundTypesRouteImport } from './routes/admin.eticketo.refund-types'
import { Route as AdminEticketoTicketsRouteImport } from './routes/admin.eticketo.tickets'
import { Route as AdminEventsCouponsRouteImport } from './routes/admin.events.coupons'
import { Route as AdminEventsDatesRouteImport } from './routes/admin.events.dates'
import { Route as AdminEventsEventsRouteImport } from './routes/admin.events.events'
import { Route as AdminEventsVenueLayoutsRouteImport } from './routes/admin.events.venue-layouts'
import { Route as AdminEventsVenuesRouteImport } from './routes/admin.events.venues'
import { Route as AdminFinancePaymentsRouteImport } from './routes/admin.finance.payments'
import { Route as AdminFinanceStatsRouteImport } from './routes/admin.finance.stats'
import { Route as AdminPosCashiersRouteImport } from './routes/admin.pos.cashiers'
import { Route as AdminPosClosingsRouteImport } from './routes/admin.pos.closings'
import { Route as AdminPosFiscalRouteImport } from './routes/admin.pos.fiscal'
import { Route as AdminPosSalesRouteImport } from './routes/admin.pos.sales'
import { Route as AdminPosTerminalsRouteImport } from './routes/admin.pos.terminals'
import { Route as AdminReportsSalesRouteImport } from './routes/admin.reports.sales'
import { Route as AdminSalesCancellationsRouteImport } from './routes/admin.sales.cancellations'
import { Route as AdminSalesNotesRouteImport } from './routes/admin.sales.notes'
import { Route as AdminSalesSalesRouteImport } from './routes/admin.sales.sales'
import { Route as AdminSystemEmailTemplatesRouteImport } from './routes/admin.system.email-templates'
import { Route as AdminSystemHealthRouteImport } from './routes/admin.system.health'
import { Route as AdminSystemPaymentsRouteImport } from './routes/admin.system.payments'
import { Route as AdminSystemUsersRouteImport } from './routes/admin.system.users'
import { Route as AdminSystemWalletRouteImport } from './routes/admin.system.wallet'
import { Route as ApiPublicSeedDemoRouteImport } from './routes/api.public.seed-demo'
import { Route as CheckoutSuccessOrderIdRouteImport } from './routes/checkout.success.$orderId'
import { Route as OrganizerEventsIndexRouteImport } from './routes/organizer.events.index'
import { Route as OrganizerEventsNewRouteImport } from './routes/organizer.events.new'
import { Route as OrganizerMarketingIndexRouteImport } from './routes/organizer.marketing.index'
import { Route as OrganizerMarketingNewRouteImport } from './routes/organizer.marketing.new'
import { Route as OrganizerPosIndexRouteImport } from './routes/organizer.pos.index'
import { Route as OrganizerPosCashierSalesRouteImport } from './routes/organizer.pos.cashier-sales'
import { Route as OrganizerPosCashiersRouteImport } from './routes/organizer.pos.cashiers'
import { Route as OrganizerPosClosingRouteImport } from './routes/organizer.pos.closing'
import { Route as OrganizerPosDevicesRouteImport } from './routes/organizer.pos.devices'
import { Route as OrganizerPosFiscalRouteImport } from './routes/organizer.pos.fiscal'
import { Route as OrganizerPosSalesRouteImport } from './routes/organizer.pos.sales'
import { Route as ApiPublicEventsByTokenRouteImport } from './routes/api.public.events.by-token'
import { Route as ApiPublicPaymentsReconcileRouteImport } from './routes/api.public.payments.reconcile'
import { Route as ApiPublicTicketsScanRouteImport } from './routes/api.public.tickets.scan'
import { Route as ApiPublicTicketsStatsRouteImport } from './routes/api.public.tickets.stats'
import { Route as ApiPublicInvoicesOrderIdPdfRouteImport } from './routes/api.public.invoices.$orderId.pdf'
import { Route as ApiPublicPaymentsGopayWebhookRouteImport } from './routes/api.public.payments.gopay.webhook'
import { Route as ApiPublicPaymentsGpwebpayReturnRouteImport } from './routes/api.public.payments.gpwebpay.return'
import { Route as ApiPublicPaymentsTatrapayplusReturnRouteImport } from './routes/api.public.payments.tatrapayplus.return'
import { Route as AdminDataCategoriesCategoryIdEventsNewRouteImport } from './routes/admin.data.categories.$categoryId.events.new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistsRoute = ArtistsRouteImport.update({
  id: '/artists',
  path: '/artists',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerRoute = OrganizerRouteImport.update({
  id: '/organizer',
  path: '/organizer',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportRoute = SupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMarketingRoute = AdminMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => AdminRoute,
} as any)
const CheckoutOrderIdRoute = CheckoutOrderIdRouteImport.update({
  id: '/checkout/$orderId',
  path: '/checkout/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => EventsRoute,
} as any)
const OrganizerIndexRoute = OrganizerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrganizerRoute,
} as any)
const OrganizerEventsRoute = OrganizerEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => OrganizerRoute,
} as any)
const OrganizerMarketingRoute = OrganizerMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => OrganizerRoute,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDataCategoriesRoute = AdminDataCategoriesRouteImport.update({
  id: '/data/categories',
  path: '/data/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDataContentRoute = AdminDataContentRouteImport.update({
  id: '/data/content',
  path: '/data/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDataGroupsRoute = AdminDataGroupsRouteImport.update({
  id: '/data/groups',
  path: '/data/groups',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDataPerformersRoute = AdminDataPerformersRouteImport.update({
  id: '/data/performers',
  path: '/data/performers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDataPriceCategoriesRoute =
  AdminDataPriceCategoriesRouteImport.update({
    id: '/data/price-categories',
    path: '/data/price-categories',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminEticketoAccountingBankRoute =
  AdminEticketoAccountingBankRouteImport.update({
    id: '/eticketo/accounting-bank',
    path: '/eticketo/accounting-bank',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminEticketoAccountingChecksRoute =
  AdminEticketoAccountingChecksRouteImport.update({
    id: '/eticketo/accounting-checks',
    path: '/eticketo/accounting-checks',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminEticketoAccountingReportRoute =
  AdminEticketoAccountingReportRouteImport.update({
    id: '/eticketo/accounting-report',
    path: '/eticketo/accounting-report',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminEticketoBalancesRoute = AdminEticketoBalancesRouteImport.update({
  id: '/eticketo/balances',
  path: '/eticketo/balances',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEticketoBillingRoute = AdminEticketoBillingRouteImport.update({
  id: '/eticketo/billing',
  path: '/eticketo/billing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEticketoControlRoute = AdminEticketoControlRouteImport.update({
  id: '/eticketo/control',
  path: '/eticketo/control',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEticketoCostsRoute = AdminEticketoCostsRouteImport.update({
  id: '/eticketo/costs',
  path: '/eticketo/costs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEticketoDevicesRoute = AdminEticketoDevicesRouteImport.update({
  id: '/eticketo/devices',
  path: '/eticketo/devices',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEticketoOrganizersRoute = AdminEticketoOrganizersRouteImport.update({
  id: '/eticketo/organizers',
  path: '/eticketo/organizers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEticketoPaymentsRoute = AdminEticketoPaymentsRouteImport.update({
  id: '/eticketo/payments',
  path: '/eticketo/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEticketoProtocolsRoute = AdminEticketoProtocolsRouteImport.update({
  id: '/eticketo/protocols',
  path: '/eticketo/protocols',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEticketoRefundTypesRoute =
  AdminEticketoRefundTypesRouteImport.update({
    id: '/eticketo/refund-types',
    path: '/eticketo/refund-types',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminEticketoTicketsRoute = AdminEticketoTicketsRouteImport.update({
  id: '/eticketo/tickets',
  path: '/eticketo/tickets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsCouponsRoute = AdminEventsCouponsRouteImport.update({
  id: '/events/coupons',
  path: '/events/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsDatesRoute = AdminEventsDatesRouteImport.update({
  id: '/events/dates',
  path: '/events/dates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsEventsRoute = AdminEventsEventsRouteImport.update({
  id: '/events/events',
  path: '/events/events',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsVenueLayoutsRoute = AdminEventsVenueLayoutsRouteImport.update({
  id: '/events/venue-layouts',
  path: '/events/venue-layouts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventsVenuesRoute = AdminEventsVenuesRouteImport.update({
  id: '/events/venues',
  path: '/events/venues',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinancePaymentsRoute = AdminFinancePaymentsRouteImport.update({
  id: '/finance/payments',
  path: '/finance/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceStatsRoute = AdminFinanceStatsRouteImport.update({
  id: '/finance/stats',
  path: '/finance/stats',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPosCashiersRoute = AdminPosCashiersRouteImport.update({
  id: '/pos/cashiers',
  path: '/pos/cashiers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPosClosingsRoute = AdminPosClosingsRouteImport.update({
  id: '/pos/closings',
  path: '/pos/closings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPosFiscalRoute = AdminPosFiscalRouteImport.update({
  id: '/pos/fiscal',
  path: '/pos/fiscal',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPosSalesRoute = AdminPosSalesRouteImport.update({
  id: '/pos/sales',
  path: '/pos/sales',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPosTerminalsRoute = AdminPosTerminalsRouteImport.update({
  id: '/pos/terminals',
  path: '/pos/terminals',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsSalesRoute = AdminReportsSalesRouteImport.update({
  id: '/reports/sales',
  path: '/reports/sales',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSalesCancellationsRoute = AdminSalesCancellationsRouteImport.update({
  id: '/sales/cancellations',
  path: '/sales/cancellations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSalesNotesRoute = AdminSalesNotesRouteImport.update({
  id: '/sales/notes',
  path: '/sales/notes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSalesSalesRoute = AdminSalesSalesRouteImport.update({
  id: '/sales/sales',
  path: '/sales/sales',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemEmailTemplatesRoute =
  AdminSystemEmailTemplatesRouteImport.update({
    id: '/system/email-templates',
    path: '/system/email-templates',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminSystemHealthRoute = AdminSystemHealthRouteImport.update({
  id: '/system/health',
  path: '/system/health',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemPaymentsRoute = AdminSystemPaymentsRouteImport.update({
  id: '/system/payments',
  path: '/system/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemUsersRoute = AdminSystemUsersRouteImport.update({
  id: '/system/users',
  path: '/system/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemWalletRoute = AdminSystemWalletRouteImport.update({
  id: '/system/wallet',
  path: '/system/wallet',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicSeedDemoRoute = ApiPublicSeedDemoRouteImport.update({
  id: '/api/public/seed-demo',
  path: '/api/public/seed-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessOrderIdRoute = CheckoutSuccessOrderIdRouteImport.update({
  id: '/checkout/success/$orderId',
  path: '/checkout/success/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizerEventsIndexRoute = OrganizerEventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrganizerEventsRoute,
} as any)
const OrganizerEventsNewRoute = OrganizerEventsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => OrganizerEventsRoute,
} as any)
const OrganizerMarketingIndexRoute = OrganizerMarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => OrganizerMarketingRoute,
} as any)
const OrganizerMarketingNewRoute = OrganizerMarketingNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => OrganizerMarketingRoute,
} as any)
const OrganizerPosIndexRoute = OrganizerPosIndexRouteImport.update({
  id: '/pos/',
  path: '/pos/',
  getParentRoute: () => OrganizerRoute,
} as any)
const OrganizerPosCashierSalesRoute =
  OrganizerPosCashierSalesRouteImport.update({
    id: '/pos/cashier-sales',
    path: '/pos/cashier-sales',
    getParentRoute: () => OrganizerRoute,
  } as any)
const OrganizerPosCashiersRoute = OrganizerPosCashiersRouteImport.update({
  id: '/pos/cashiers',
  path: '/pos/cashiers',
  getParentRoute: () => OrganizerRoute,
} as any)
const OrganizerPosClosingRoute = OrganizerPosClosingRouteImport.update({
  id: '/pos/closing',
  path: '/pos/closing',
  getParentRoute: () => OrganizerRoute,
} as any)
const OrganizerPosDevicesRoute = OrganizerPosDevicesRouteImport.update({
  id: '/pos/devices',
  path: '/pos/devices',
  getParentRoute: () => OrganizerRoute,
} as any)
const OrganizerPosFiscalRoute = OrganizerPosFiscalRouteImport.update({
  id: '/pos/fiscal',
  path: '/pos/fiscal',
  getParentRoute: () => OrganizerRoute,
} as any)
const OrganizerPosSalesRoute = OrganizerPosSalesRouteImport.update({
  id: '/pos/sales',
  path: '/pos/sales',
  getParentRoute: () => OrganizerRoute,
} as any)
const ApiPublicEventsByTokenRoute = ApiPublicEventsByTokenRouteImport.update({
  id: '/api/public/events/by-token',
  path: '/api/public/events/by-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsReconcileRoute =
  ApiPublicPaymentsReconcileRouteImport.update({
    id: '/api/public/payments/reconcile',
    path: '/api/public/payments/reconcile',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTicketsScanRoute = ApiPublicTicketsScanRouteImport.update({
  id: '/api/public/tickets/scan',
  path: '/api/public/tickets/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTicketsStatsRoute = ApiPublicTicketsStatsRouteImport.update({
  id: '/api/public/tickets/stats',
  path: '/api/public/tickets/stats',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInvoicesOrderIdPdfRoute =
  ApiPublicInvoicesOrderIdPdfRouteImport.update({
    id: '/api/public/invoices/$orderId/pdf',
    path: '/api/public/invoices/$orderId/pdf',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsGopayWebhookRoute =
  ApiPublicPaymentsGopayWebhookRouteImport.update({
    id: '/api/public/payments/gopay/webhook',
    path: '/api/public/payments/gopay/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsGpwebpayReturnRoute =
  ApiPublicPaymentsGpwebpayReturnRouteImport.update({
    id: '/api/public/payments/gpwebpay/return',
    path: '/api/public/payments/gpwebpay/return',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsTatrapayplusReturnRoute =
  ApiPublicPaymentsTatrapayplusReturnRouteImport.update({
    id: '/api/public/payments/tatrapayplus/return',
    path: '/api/public/payments/tatrapayplus/return',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminDataCategoriesCategoryIdEventsNewRoute =
  AdminDataCategoriesCategoryIdEventsNewRouteImport.update({
    id: '/$categoryId/events/new',
    path: '/$categoryId/events/new',
    getParentRoute: () => AdminDataCategoriesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/artists': typeof ArtistsRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/organizer': typeof OrganizerRouteWithChildren
  '/partners': typeof PartnersRoute
  '/register': typeof RegisterRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/scanner': typeof ScannerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/checkout/$orderId': typeof CheckoutOrderIdRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/events/$id': typeof EventsIdRoute
  '/organizer/events': typeof OrganizerEventsRouteWithChildren
  '/organizer/marketing': typeof OrganizerMarketingRouteWithChildren
  '/p/$slug': typeof PSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/organizer/': typeof OrganizerIndexRoute
  '/admin/data/categories': typeof AdminDataCategoriesRouteWithChildren
  '/admin/data/content': typeof AdminDataContentRoute
  '/admin/data/groups': typeof AdminDataGroupsRoute
  '/admin/data/performers': typeof AdminDataPerformersRoute
  '/admin/data/price-categories': typeof AdminDataPriceCategoriesRoute
  '/admin/eticketo/accounting-bank': typeof AdminEticketoAccountingBankRoute
  '/admin/eticketo/accounting-checks': typeof AdminEticketoAccountingChecksRoute
  '/admin/eticketo/accounting-report': typeof AdminEticketoAccountingReportRoute
  '/admin/eticketo/balances': typeof AdminEticketoBalancesRoute
  '/admin/eticketo/billing': typeof AdminEticketoBillingRoute
  '/admin/eticketo/control': typeof AdminEticketoControlRoute
  '/admin/eticketo/costs': typeof AdminEticketoCostsRoute
  '/admin/eticketo/devices': typeof AdminEticketoDevicesRoute
  '/admin/eticketo/organizers': typeof AdminEticketoOrganizersRoute
  '/admin/eticketo/payments': typeof AdminEticketoPaymentsRoute
  '/admin/eticketo/protocols': typeof AdminEticketoProtocolsRoute
  '/admin/eticketo/refund-types': typeof AdminEticketoRefundTypesRoute
  '/admin/eticketo/tickets': typeof AdminEticketoTicketsRoute
  '/admin/events/coupons': typeof AdminEventsCouponsRoute
  '/admin/events/dates': typeof AdminEventsDatesRoute
  '/admin/events/events': typeof AdminEventsEventsRoute
  '/admin/events/venue-layouts': typeof AdminEventsVenueLayoutsRoute
  '/admin/events/venues': typeof AdminEventsVenuesRoute
  '/admin/finance/payments': typeof AdminFinancePaymentsRoute
  '/admin/finance/stats': typeof AdminFinanceStatsRoute
  '/admin/pos/cashiers': typeof AdminPosCashiersRoute
  '/admin/pos/closings': typeof AdminPosClosingsRoute
  '/admin/pos/fiscal': typeof AdminPosFiscalRoute
  '/admin/pos/sales': typeof AdminPosSalesRoute
  '/admin/pos/terminals': typeof AdminPosTerminalsRoute
  '/admin/reports/sales': typeof AdminReportsSalesRoute
  '/admin/sales/cancellations': typeof AdminSalesCancellationsRoute
  '/admin/sales/notes': typeof AdminSalesNotesRoute
  '/admin/sales/sales': typeof AdminSalesSalesRoute
  '/admin/system/email-templates': typeof AdminSystemEmailTemplatesRoute
  '/admin/system/health': typeof AdminSystemHealthRoute
  '/admin/system/payments': typeof AdminSystemPaymentsRoute
  '/admin/system/users': typeof AdminSystemUsersRoute
  '/admin/system/wallet': typeof AdminSystemWalletRoute
  '/api/public/seed-demo': typeof ApiPublicSeedDemoRoute
  '/checkout/success/$orderId': typeof CheckoutSuccessOrderIdRoute
  '/organizer/events/new': typeof OrganizerEventsNewRoute
  '/organizer/marketing/new': typeof OrganizerMarketingNewRoute
  '/organizer/pos/cashier-sales': typeof OrganizerPosCashierSalesRoute
  '/organizer/pos/cashiers': typeof OrganizerPosCashiersRoute
  '/organizer/pos/closing': typeof OrganizerPosClosingRoute
  '/organizer/pos/devices': typeof OrganizerPosDevicesRoute
  '/organizer/pos/fiscal': typeof OrganizerPosFiscalRoute
  '/organizer/pos/sales': typeof OrganizerPosSalesRoute
  '/organizer/events/': typeof OrganizerEventsIndexRoute
  '/organizer/marketing/': typeof OrganizerMarketingIndexRoute
  '/organizer/pos/': typeof OrganizerPosIndexRoute
  '/api/public/events/by-token': typeof ApiPublicEventsByTokenRoute
  '/api/public/payments/reconcile': typeof ApiPublicPaymentsReconcileRoute
  '/api/public/tickets/scan': typeof ApiPublicTicketsScanRoute
  '/api/public/tickets/stats': typeof ApiPublicTicketsStatsRoute
  '/api/public/invoices/$orderId/pdf': typeof ApiPublicInvoicesOrderIdPdfRoute
  '/api/public/payments/gopay/webhook': typeof ApiPublicPaymentsGopayWebhookRoute
  '/api/public/payments/gpwebpay/return': typeof ApiPublicPaymentsGpwebpayReturnRoute
  '/api/public/payments/tatrapayplus/return': typeof ApiPublicPaymentsTatrapayplusReturnRoute
  '/admin/data/categories/$categoryId/events/new': typeof AdminDataCategoriesCategoryIdEventsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/artists': typeof ArtistsRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/partners': typeof PartnersRoute
  '/register': typeof RegisterRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/scanner': typeof ScannerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/checkout/$orderId': typeof CheckoutOrderIdRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/events/$id': typeof EventsIdRoute
  '/p/$slug': typeof PSlugRoute
  '/admin': typeof AdminIndexRoute
  '/organizer': typeof OrganizerIndexRoute
  '/admin/data/categories': typeof AdminDataCategoriesRouteWithChildren
  '/admin/data/content': typeof AdminDataContentRoute
  '/admin/data/groups': typeof AdminDataGroupsRoute
  '/admin/data/performers': typeof AdminDataPerformersRoute
  '/admin/data/price-categories': typeof AdminDataPriceCategoriesRoute
  '/admin/eticketo/accounting-bank': typeof AdminEticketoAccountingBankRoute
  '/admin/eticketo/accounting-checks': typeof AdminEticketoAccountingChecksRoute
  '/admin/eticketo/accounting-report': typeof AdminEticketoAccountingReportRoute
  '/admin/eticketo/balances': typeof AdminEticketoBalancesRoute
  '/admin/eticketo/billing': typeof AdminEticketoBillingRoute
  '/admin/eticketo/control': typeof AdminEticketoControlRoute
  '/admin/eticketo/costs': typeof AdminEticketoCostsRoute
  '/admin/eticketo/devices': typeof AdminEticketoDevicesRoute
  '/admin/eticketo/organizers': typeof AdminEticketoOrganizersRoute
  '/admin/eticketo/payments': typeof AdminEticketoPaymentsRoute
  '/admin/eticketo/protocols': typeof AdminEticketoProtocolsRoute
  '/admin/eticketo/refund-types': typeof AdminEticketoRefundTypesRoute
  '/admin/eticketo/tickets': typeof AdminEticketoTicketsRoute
  '/admin/events/coupons': typeof AdminEventsCouponsRoute
  '/admin/events/dates': typeof AdminEventsDatesRoute
  '/admin/events/events': typeof AdminEventsEventsRoute
  '/admin/events/venue-layouts': typeof AdminEventsVenueLayoutsRoute
  '/admin/events/venues': typeof AdminEventsVenuesRoute
  '/admin/finance/payments': typeof AdminFinancePaymentsRoute
  '/admin/finance/stats': typeof AdminFinanceStatsRoute
  '/admin/pos/cashiers': typeof AdminPosCashiersRoute
  '/admin/pos/closings': typeof AdminPosClosingsRoute
  '/admin/pos/fiscal': typeof AdminPosFiscalRoute
  '/admin/pos/sales': typeof AdminPosSalesRoute
  '/admin/pos/terminals': typeof AdminPosTerminalsRoute
  '/admin/reports/sales': typeof AdminReportsSalesRoute
  '/admin/sales/cancellations': typeof AdminSalesCancellationsRoute
  '/admin/sales/notes': typeof AdminSalesNotesRoute
  '/admin/sales/sales': typeof AdminSalesSalesRoute
  '/admin/system/email-templates': typeof AdminSystemEmailTemplatesRoute
  '/admin/system/health': typeof AdminSystemHealthRoute
  '/admin/system/payments': typeof AdminSystemPaymentsRoute
  '/admin/system/users': typeof AdminSystemUsersRoute
  '/admin/system/wallet': typeof AdminSystemWalletRoute
  '/api/public/seed-demo': typeof ApiPublicSeedDemoRoute
  '/checkout/success/$orderId': typeof CheckoutSuccessOrderIdRoute
  '/organizer/events/new': typeof OrganizerEventsNewRoute
  '/organizer/marketing/new': typeof OrganizerMarketingNewRoute
  '/organizer/pos/cashier-sales': typeof OrganizerPosCashierSalesRoute
  '/organizer/pos/cashiers': typeof OrganizerPosCashiersRoute
  '/organizer/pos/closing': typeof OrganizerPosClosingRoute
  '/organizer/pos/devices': typeof OrganizerPosDevicesRoute
  '/organizer/pos/fiscal': typeof OrganizerPosFiscalRoute
  '/organizer/pos/sales': typeof OrganizerPosSalesRoute
  '/organizer/events': typeof OrganizerEventsIndexRoute
  '/organizer/marketing': typeof OrganizerMarketingIndexRoute
  '/organizer/pos': typeof OrganizerPosIndexRoute
  '/api/public/events/by-token': typeof ApiPublicEventsByTokenRoute
  '/api/public/payments/reconcile': typeof ApiPublicPaymentsReconcileRoute
  '/api/public/tickets/scan': typeof ApiPublicTicketsScanRoute
  '/api/public/tickets/stats': typeof ApiPublicTicketsStatsRoute
  '/api/public/invoices/$orderId/pdf': typeof ApiPublicInvoicesOrderIdPdfRoute
  '/api/public/payments/gopay/webhook': typeof ApiPublicPaymentsGopayWebhookRoute
  '/api/public/payments/gpwebpay/return': typeof ApiPublicPaymentsGpwebpayReturnRoute
  '/api/public/payments/tatrapayplus/return': typeof ApiPublicPaymentsTatrapayplusReturnRoute
  '/admin/data/categories/$categoryId/events/new': typeof AdminDataCategoriesCategoryIdEventsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRouteWithChildren
  '/artists': typeof ArtistsRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRouteWithChildren
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/organizer': typeof OrganizerRouteWithChildren
  '/partners': typeof PartnersRoute
  '/register': typeof RegisterRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/scanner': typeof ScannerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/support': typeof SupportRoute
  '/admin/marketing': typeof AdminMarketingRoute
  '/checkout/$orderId': typeof CheckoutOrderIdRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/events/$id': typeof EventsIdRoute
  '/organizer/events': typeof OrganizerEventsRouteWithChildren
  '/organizer/marketing': typeof OrganizerMarketingRouteWithChildren
  '/p/$slug': typeof PSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/organizer/': typeof OrganizerIndexRoute
  '/admin/data/categories': typeof AdminDataCategoriesRouteWithChildren
  '/admin/data/content': typeof AdminDataContentRoute
  '/admin/data/groups': typeof AdminDataGroupsRoute
  '/admin/data/performers': typeof AdminDataPerformersRoute
  '/admin/data/price-categories': typeof AdminDataPriceCategoriesRoute
  '/admin/eticketo/accounting-bank': typeof AdminEticketoAccountingBankRoute
  '/admin/eticketo/accounting-checks': typeof AdminEticketoAccountingChecksRoute
  '/admin/eticketo/accounting-report': typeof AdminEticketoAccountingReportRoute
  '/admin/eticketo/balances': typeof AdminEticketoBalancesRoute
  '/admin/eticketo/billing': typeof AdminEticketoBillingRoute
  '/admin/eticketo/control': typeof AdminEticketoControlRoute
  '/admin/eticketo/costs': typeof AdminEticketoCostsRoute
  '/admin/eticketo/devices': typeof AdminEticketoDevicesRoute
  '/admin/eticketo/organizers': typeof AdminEticketoOrganizersRoute
  '/admin/eticketo/payments': typeof AdminEticketoPaymentsRoute
  '/admin/eticketo/protocols': typeof AdminEticketoProtocolsRoute
  '/admin/eticketo/refund-types': typeof AdminEticketoRefundTypesRoute
  '/admin/eticketo/tickets': typeof AdminEticketoTicketsRoute
  '/admin/events/coupons': typeof AdminEventsCouponsRoute
  '/admin/events/dates': typeof AdminEventsDatesRoute
  '/admin/events/events': typeof AdminEventsEventsRoute
  '/admin/events/venue-layouts': typeof AdminEventsVenueLayoutsRoute
  '/admin/events/venues': typeof AdminEventsVenuesRoute
  '/admin/finance/payments': typeof AdminFinancePaymentsRoute
  '/admin/finance/stats': typeof AdminFinanceStatsRoute
  '/admin/pos/cashiers': typeof AdminPosCashiersRoute
  '/admin/pos/closings': typeof AdminPosClosingsRoute
  '/admin/pos/fiscal': typeof AdminPosFiscalRoute
  '/admin/pos/sales': typeof AdminPosSalesRoute
  '/admin/pos/terminals': typeof AdminPosTerminalsRoute
  '/admin/reports/sales': typeof AdminReportsSalesRoute
  '/admin/sales/cancellations': typeof AdminSalesCancellationsRoute
  '/admin/sales/notes': typeof AdminSalesNotesRoute
  '/admin/sales/sales': typeof AdminSalesSalesRoute
  '/admin/system/email-templates': typeof AdminSystemEmailTemplatesRoute
  '/admin/system/health': typeof AdminSystemHealthRoute
  '/admin/system/payments': typeof AdminSystemPaymentsRoute
  '/admin/system/users': typeof AdminSystemUsersRoute
  '/admin/system/wallet': typeof AdminSystemWalletRoute
  '/api/public/seed-demo': typeof ApiPublicSeedDemoRoute
  '/checkout/success/$orderId': typeof CheckoutSuccessOrderIdRoute
  '/organizer/events/new': typeof OrganizerEventsNewRoute
  '/organizer/marketing/new': typeof OrganizerMarketingNewRoute
  '/organizer/pos/cashier-sales': typeof OrganizerPosCashierSalesRoute
  '/organizer/pos/cashiers': typeof OrganizerPosCashiersRoute
  '/organizer/pos/closing': typeof OrganizerPosClosingRoute
  '/organizer/pos/devices': typeof OrganizerPosDevicesRoute
  '/organizer/pos/fiscal': typeof OrganizerPosFiscalRoute
  '/organizer/pos/sales': typeof OrganizerPosSalesRoute
  '/organizer/events/': typeof OrganizerEventsIndexRoute
  '/organizer/marketing/': typeof OrganizerMarketingIndexRoute
  '/organizer/pos/': typeof OrganizerPosIndexRoute
  '/api/public/events/by-token': typeof ApiPublicEventsByTokenRoute
  '/api/public/payments/reconcile': typeof ApiPublicPaymentsReconcileRoute
  '/api/public/tickets/scan': typeof ApiPublicTicketsScanRoute
  '/api/public/tickets/stats': typeof ApiPublicTicketsStatsRoute
  '/api/public/invoices/$orderId/pdf': typeof ApiPublicInvoicesOrderIdPdfRoute
  '/api/public/payments/gopay/webhook': typeof ApiPublicPaymentsGopayWebhookRoute
  '/api/public/payments/gpwebpay/return': typeof ApiPublicPaymentsGpwebpayReturnRoute
  '/api/public/payments/tatrapayplus/return': typeof ApiPublicPaymentsTatrapayplusReturnRoute
  '/admin/data/categories/$categoryId/events/new': typeof AdminDataCategoriesCategoryIdEventsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/artists'
    | '/contact'
    | '/events'
    | '/login'
    | '/marketing'
    | '/organizer'
    | '/partners'
    | '/register'
    | '/robots.txt'
    | '/scanner'
    | '/sitemap.xml'
    | '/support'
    | '/admin/marketing'
    | '/checkout/$orderId'
    | '/checkout/return'
    | '/events/$id'
    | '/organizer/events'
    | '/organizer/marketing'
    | '/p/$slug'
    | '/admin/'
    | '/organizer/'
    | '/admin/data/categories'
    | '/admin/data/content'
    | '/admin/data/groups'
    | '/admin/data/performers'
    | '/admin/data/price-categories'
    | '/admin/eticketo/accounting-bank'
    | '/admin/eticketo/accounting-checks'
    | '/admin/eticketo/accounting-report'
    | '/admin/eticketo/balances'
    | '/admin/eticketo/billing'
    | '/admin/eticketo/control'
    | '/admin/eticketo/costs'
    | '/admin/eticketo/devices'
    | '/admin/eticketo/organizers'
    | '/admin/eticketo/payments'
    | '/admin/eticketo/protocols'
    | '/admin/eticketo/refund-types'
    | '/admin/eticketo/tickets'
    | '/admin/events/coupons'
    | '/admin/events/dates'
    | '/admin/events/events'
    | '/admin/events/venue-layouts'
    | '/admin/events/venues'
    | '/admin/finance/payments'
    | '/admin/finance/stats'
    | '/admin/pos/cashiers'
    | '/admin/pos/closings'
    | '/admin/pos/fiscal'
    | '/admin/pos/sales'
    | '/admin/pos/terminals'
    | '/admin/reports/sales'
    | '/admin/sales/cancellations'
    | '/admin/sales/notes'
    | '/admin/sales/sales'
    | '/admin/system/email-templates'
    | '/admin/system/health'
    | '/admin/system/payments'
    | '/admin/system/users'
    | '/admin/system/wallet'
    | '/api/public/seed-demo'
    | '/checkout/success/$orderId'
    | '/organizer/events/new'
    | '/organizer/marketing/new'
    | '/organizer/pos/cashier-sales'
    | '/organizer/pos/cashiers'
    | '/organizer/pos/closing'
    | '/organizer/pos/devices'
    | '/organizer/pos/fiscal'
    | '/organizer/pos/sales'
    | '/organizer/events/'
    | '/organizer/marketing/'
    | '/organizer/pos/'
    | '/api/public/events/by-token'
    | '/api/public/payments/reconcile'
    | '/api/public/tickets/scan'
    | '/api/public/tickets/stats'
    | '/api/public/invoices/$orderId/pdf'
    | '/api/public/payments/gopay/webhook'
    | '/api/public/payments/gpwebpay/return'
    | '/api/public/payments/tatrapayplus/return'
    | '/admin/data/categories/$categoryId/events/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/artists'
    | '/contact'
    | '/events'
    | '/login'
    | '/marketing'
    | '/partners'
    | '/register'
    | '/robots.txt'
    | '/scanner'
    | '/sitemap.xml'
    | '/support'
    | '/admin/marketing'
    | '/checkout/$orderId'
    | '/checkout/return'
    | '/events/$id'
    | '/p/$slug'
    | '/admin'
    | '/organizer'
    | '/admin/data/categories'
    | '/admin/data/content'
    | '/admin/data/groups'
    | '/admin/data/performers'
    | '/admin/data/price-categories'
    | '/admin/eticketo/accounting-bank'
    | '/admin/eticketo/accounting-checks'
    | '/admin/eticketo/accounting-report'
    | '/admin/eticketo/balances'
    | '/admin/eticketo/billing'
    | '/admin/eticketo/control'
    | '/admin/eticketo/costs'
    | '/admin/eticketo/devices'
    | '/admin/eticketo/organizers'
    | '/admin/eticketo/payments'
    | '/admin/eticketo/protocols'
    | '/admin/eticketo/refund-types'
    | '/admin/eticketo/tickets'
    | '/admin/events/coupons'
    | '/admin/events/dates'
    | '/admin/events/events'
    | '/admin/events/venue-layouts'
    | '/admin/events/venues'
    | '/admin/finance/payments'
    | '/admin/finance/stats'
    | '/admin/pos/cashiers'
    | '/admin/pos/closings'
    | '/admin/pos/fiscal'
    | '/admin/pos/sales'
    | '/admin/pos/terminals'
    | '/admin/reports/sales'
    | '/admin/sales/cancellations'
    | '/admin/sales/notes'
    | '/admin/sales/sales'
    | '/admin/system/email-templates'
    | '/admin/system/health'
    | '/admin/system/payments'
    | '/admin/system/users'
    | '/admin/system/wallet'
    | '/api/public/seed-demo'
    | '/checkout/success/$orderId'
    | '/organizer/events/new'
    | '/organizer/marketing/new'
    | '/organizer/pos/cashier-sales'
    | '/organizer/pos/cashiers'
    | '/organizer/pos/closing'
    | '/organizer/pos/devices'
    | '/organizer/pos/fiscal'
    | '/organizer/pos/sales'
    | '/organizer/events'
    | '/organizer/marketing'
    | '/organizer/pos'
    | '/api/public/events/by-token'
    | '/api/public/payments/reconcile'
    | '/api/public/tickets/scan'
    | '/api/public/tickets/stats'
    | '/api/public/invoices/$orderId/pdf'
    | '/api/public/payments/gopay/webhook'
    | '/api/public/payments/gpwebpay/return'
    | '/api/public/payments/tatrapayplus/return'
    | '/admin/data/categories/$categoryId/events/new'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/artists'
    | '/contact'
    | '/events'
    | '/login'
    | '/marketing'
    | '/organizer'
    | '/partners'
    | '/register'
    | '/robots.txt'
    | '/scanner'
    | '/sitemap.xml'
    | '/support'
    | '/admin/marketing'
    | '/checkout/$orderId'
    | '/checkout/return'
    | '/events/$id'
    | '/organizer/events'
    | '/organizer/marketing'
    | '/p/$slug'
    | '/admin/'
    | '/organizer/'
    | '/admin/data/categories'
    | '/admin/data/content'
    | '/admin/data/groups'
    | '/admin/data/performers'
    | '/admin/data/price-categories'
    | '/admin/eticketo/accounting-bank'
    | '/admin/eticketo/accounting-checks'
    | '/admin/eticketo/accounting-report'
    | '/admin/eticketo/balances'
    | '/admin/eticketo/billing'
    | '/admin/eticketo/control'
    | '/admin/eticketo/costs'
    | '/admin/eticketo/devices'
    | '/admin/eticketo/organizers'
    | '/admin/eticketo/payments'
    | '/admin/eticketo/protocols'
    | '/admin/eticketo/refund-types'
    | '/admin/eticketo/tickets'
    | '/admin/events/coupons'
    | '/admin/events/dates'
    | '/admin/events/events'
    | '/admin/events/venue-layouts'
    | '/admin/events/venues'
    | '/admin/finance/payments'
    | '/admin/finance/stats'
    | '/admin/pos/cashiers'
    | '/admin/pos/closings'
    | '/admin/pos/fiscal'
    | '/admin/pos/sales'
    | '/admin/pos/terminals'
    | '/admin/reports/sales'
    | '/admin/sales/cancellations'
    | '/admin/sales/notes'
    | '/admin/sales/sales'
    | '/admin/system/email-templates'
    | '/admin/system/health'
    | '/admin/system/payments'
    | '/admin/system/users'
    | '/admin/system/wallet'
    | '/api/public/seed-demo'
    | '/checkout/success/$orderId'
    | '/organizer/events/new'
    | '/organizer/marketing/new'
    | '/organizer/pos/cashier-sales'
    | '/organizer/pos/cashiers'
    | '/organizer/pos/closing'
    | '/organizer/pos/devices'
    | '/organizer/pos/fiscal'
    | '/organizer/pos/sales'
    | '/organizer/events/'
    | '/organizer/marketing/'
    | '/organizer/pos/'
    | '/api/public/events/by-token'
    | '/api/public/payments/reconcile'
    | '/api/public/tickets/scan'
    | '/api/public/tickets/stats'
    | '/api/public/invoices/$orderId/pdf'
    | '/api/public/payments/gopay/webhook'
    | '/api/public/payments/gpwebpay/return'
    | '/api/public/payments/tatrapayplus/return'
    | '/admin/data/categories/$categoryId/events/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRouteWithChildren
  ArtistsRoute: typeof ArtistsRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRouteWithChildren
  LoginRoute: typeof LoginRoute
  MarketingRoute: typeof MarketingRoute
  OrganizerRoute: typeof OrganizerRouteWithChildren
  PartnersRoute: typeof PartnersRoute
  RegisterRoute: typeof RegisterRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ScannerRoute: typeof ScannerRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SupportRoute: typeof SupportRoute
  CheckoutOrderIdRoute: typeof CheckoutOrderIdRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  PSlugRoute: typeof PSlugRoute
  ApiPublicSeedDemoRoute: typeof ApiPublicSeedDemoRoute
  CheckoutSuccessOrderIdRoute: typeof CheckoutSuccessOrderIdRoute
  ApiPublicEventsByTokenRoute: typeof ApiPublicEventsByTokenRoute
  ApiPublicPaymentsReconcileRoute: typeof ApiPublicPaymentsReconcileRoute
  ApiPublicTicketsScanRoute: typeof ApiPublicTicketsScanRoute
  ApiPublicTicketsStatsRoute: typeof ApiPublicTicketsStatsRoute
  ApiPublicInvoicesOrderIdPdfRoute: typeof ApiPublicInvoicesOrderIdPdfRoute
  ApiPublicPaymentsGopayWebhookRoute: typeof ApiPublicPaymentsGopayWebhookRoute
  ApiPublicPaymentsGpwebpayReturnRoute: typeof ApiPublicPaymentsGpwebpayReturnRoute
  ApiPublicPaymentsTatrapayplusReturnRoute: typeof ApiPublicPaymentsTatrapayplusReturnRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artists': {
      id: '/artists'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof ArtistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer': {
      id: '/organizer'
      path: '/organizer'
      fullPath: '/organizer'
      preLoaderRoute: typeof OrganizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support': {
      id: '/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof SupportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/marketing': {
      id: '/admin/marketing'
      path: '/marketing'
      fullPath: '/admin/marketing'
      preLoaderRoute: typeof AdminMarketingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/checkout/$orderId': {
      id: '/checkout/$orderId'
      path: '/checkout/$orderId'
      fullPath: '/checkout/$orderId'
      preLoaderRoute: typeof CheckoutOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof EventsRoute
    }
    '/organizer/': {
      id: '/organizer/'
      path: '/'
      fullPath: '/organizer/'
      preLoaderRoute: typeof OrganizerIndexRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/organizer/events': {
      id: '/organizer/events'
      path: '/events'
      fullPath: '/organizer/events'
      preLoaderRoute: typeof OrganizerEventsRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/organizer/marketing': {
      id: '/organizer/marketing'
      path: '/marketing'
      fullPath: '/organizer/marketing'
      preLoaderRoute: typeof OrganizerMarketingRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/data/categories': {
      id: '/admin/data/categories'
      path: '/data/categories'
      fullPath: '/admin/data/categories'
      preLoaderRoute: typeof AdminDataCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/data/content': {
      id: '/admin/data/content'
      path: '/data/content'
      fullPath: '/admin/data/content'
      preLoaderRoute: typeof AdminDataContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/data/groups': {
      id: '/admin/data/groups'
      path: '/data/groups'
      fullPath: '/admin/data/groups'
      preLoaderRoute: typeof AdminDataGroupsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/data/performers': {
      id: '/admin/data/performers'
      path: '/data/performers'
      fullPath: '/admin/data/performers'
      preLoaderRoute: typeof AdminDataPerformersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/data/price-categories': {
      id: '/admin/data/price-categories'
      path: '/data/price-categories'
      fullPath: '/admin/data/price-categories'
      preLoaderRoute: typeof AdminDataPriceCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/eticketo/accounting-bank': {
      id: '/admin/eticketo/accounting-bank'
      path: '/eticketo/accounting-bank'
      fullPath: '/admin/eticketo/accounting-bank'
      preLoaderRoute: typeof AdminEticketoAccountingBankRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/eticketo/accounting-checks': {
      id: '/admin/eticketo/accounting-checks'
      path: '/eticketo/accounting-checks'
      fullPath: '/admin/eticketo/accounting-checks'
      preLoaderRoute: typeof AdminEticketoAccountingChecksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/eticketo/accounting-report': {
      id: '/admin/eticketo/accounting-report'
      path: '/eticketo/accounting-report'
      fullPath: '/admin/eticketo/accounting-report'
      preLoaderRoute: typeof AdminEticketoAccountingReportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/eticketo/balances': {
      id: '/admin/eticketo/balances'
      path: '/eticketo/balances'
      fullPath: '/admin/eticketo/balances'
      preLoaderRoute: typeof AdminEticketoBalancesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/eticketo/billing': {
      id: '/admin/eticketo/billing'
      path: '/eticketo/billing'
      fullPath: '/admin/eticketo/billing'
      preLoaderRoute: typeof AdminEticketoBillingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/eticketo/control': {
      id: '/admin/eticketo/control'
      path: '/eticketo/control'
      fullPath: '/admin/eticketo/control'
      preLoaderRoute: typeof AdminEticketoControlRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/eticketo/costs': {
      id: '/admin/eticketo/costs'
      path: '/eticketo/costs'
      fullPath: '/admin/eticketo/costs'
      preLoaderRoute: typeof AdminEticketoCostsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/eticketo/devices': {
      id: '/admin/eticketo/devices'
      path: '/eticketo/devices'
      fullPath: '/admin/eticketo/devices'
      preLoaderRoute: typeof AdminEticketoDevicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/eticketo/organizers': {
      id: '/admin/eticketo/organizers'
      path: '/eticketo/organizers'
      fullPath: '/admin/eticketo/organizers'
      preLoaderRoute: typeof AdminEticketoOrganizersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/eticketo/payments': {
      id: '/admin/eticketo/payments'
      path: '/eticketo/payments'
      fullPath: '/admin/eticketo/payments'
      preLoaderRoute: typeof AdminEticketoPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/eticketo/protocols': {
      id: '/admin/eticketo/protocols'
      path: '/eticketo/protocols'
      fullPath: '/admin/eticketo/protocols'
      preLoaderRoute: typeof AdminEticketoProtocolsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/eticketo/refund-types': {
      id: '/admin/eticketo/refund-types'
      path: '/eticketo/refund-types'
      fullPath: '/admin/eticketo/refund-types'
      preLoaderRoute: typeof AdminEticketoRefundTypesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/eticketo/tickets': {
      id: '/admin/eticketo/tickets'
      path: '/eticketo/tickets'
      fullPath: '/admin/eticketo/tickets'
      preLoaderRoute: typeof AdminEticketoTicketsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/coupons': {
      id: '/admin/events/coupons'
      path: '/events/coupons'
      fullPath: '/admin/events/coupons'
      preLoaderRoute: typeof AdminEventsCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/dates': {
      id: '/admin/events/dates'
      path: '/events/dates'
      fullPath: '/admin/events/dates'
      preLoaderRoute: typeof AdminEventsDatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/events': {
      id: '/admin/events/events'
      path: '/events/events'
      fullPath: '/admin/events/events'
      preLoaderRoute: typeof AdminEventsEventsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/venue-layouts': {
      id: '/admin/events/venue-layouts'
      path: '/events/venue-layouts'
      fullPath: '/admin/events/venue-layouts'
      preLoaderRoute: typeof AdminEventsVenueLayoutsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/events/venues': {
      id: '/admin/events/venues'
      path: '/events/venues'
      fullPath: '/admin/events/venues'
      preLoaderRoute: typeof AdminEventsVenuesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance/payments': {
      id: '/admin/finance/payments'
      path: '/finance/payments'
      fullPath: '/admin/finance/payments'
      preLoaderRoute: typeof AdminFinancePaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance/stats': {
      id: '/admin/finance/stats'
      path: '/finance/stats'
      fullPath: '/admin/finance/stats'
      preLoaderRoute: typeof AdminFinanceStatsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pos/cashiers': {
      id: '/admin/pos/cashiers'
      path: '/pos/cashiers'
      fullPath: '/admin/pos/cashiers'
      preLoaderRoute: typeof AdminPosCashiersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pos/closings': {
      id: '/admin/pos/closings'
      path: '/pos/closings'
      fullPath: '/admin/pos/closings'
      preLoaderRoute: typeof AdminPosClosingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pos/fiscal': {
      id: '/admin/pos/fiscal'
      path: '/pos/fiscal'
      fullPath: '/admin/pos/fiscal'
      preLoaderRoute: typeof AdminPosFiscalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pos/sales': {
      id: '/admin/pos/sales'
      path: '/pos/sales'
      fullPath: '/admin/pos/sales'
      preLoaderRoute: typeof AdminPosSalesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pos/terminals': {
      id: '/admin/pos/terminals'
      path: '/pos/terminals'
      fullPath: '/admin/pos/terminals'
      preLoaderRoute: typeof AdminPosTerminalsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports/sales': {
      id: '/admin/reports/sales'
      path: '/reports/sales'
      fullPath: '/admin/reports/sales'
      preLoaderRoute: typeof AdminReportsSalesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sales/cancellations': {
      id: '/admin/sales/cancellations'
      path: '/sales/cancellations'
      fullPath: '/admin/sales/cancellations'
      preLoaderRoute: typeof AdminSalesCancellationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sales/notes': {
      id: '/admin/sales/notes'
      path: '/sales/notes'
      fullPath: '/admin/sales/notes'
      preLoaderRoute: typeof AdminSalesNotesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sales/sales': {
      id: '/admin/sales/sales'
      path: '/sales/sales'
      fullPath: '/admin/sales/sales'
      preLoaderRoute: typeof AdminSalesSalesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system/email-templates': {
      id: '/admin/system/email-templates'
      path: '/system/email-templates'
      fullPath: '/admin/system/email-templates'
      preLoaderRoute: typeof AdminSystemEmailTemplatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system/health': {
      id: '/admin/system/health'
      path: '/system/health'
      fullPath: '/admin/system/health'
      preLoaderRoute: typeof AdminSystemHealthRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system/payments': {
      id: '/admin/system/payments'
      path: '/system/payments'
      fullPath: '/admin/system/payments'
      preLoaderRoute: typeof AdminSystemPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system/users': {
      id: '/admin/system/users'
      path: '/system/users'
      fullPath: '/admin/system/users'
      preLoaderRoute: typeof AdminSystemUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system/wallet': {
      id: '/admin/system/wallet'
      path: '/system/wallet'
      fullPath: '/admin/system/wallet'
      preLoaderRoute: typeof AdminSystemWalletRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/seed-demo': {
      id: '/api/public/seed-demo'
      path: '/api/public/seed-demo'
      fullPath: '/api/public/seed-demo'
      preLoaderRoute: typeof ApiPublicSeedDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success/$orderId': {
      id: '/checkout/success/$orderId'
      path: '/checkout/success/$orderId'
      fullPath: '/checkout/success/$orderId'
      preLoaderRoute: typeof CheckoutSuccessOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizer/events/': {
      id: '/organizer/events/'
      path: '/'
      fullPath: '/organizer/events/'
      preLoaderRoute: typeof OrganizerEventsIndexRouteImport
      parentRoute: typeof OrganizerEventsRoute
    }
    '/organizer/events/new': {
      id: '/organizer/events/new'
      path: '/new'
      fullPath: '/organizer/events/new'
      preLoaderRoute: typeof OrganizerEventsNewRouteImport
      parentRoute: typeof OrganizerEventsRoute
    }
    '/organizer/marketing/': {
      id: '/organizer/marketing/'
      path: '/'
      fullPath: '/organizer/marketing/'
      preLoaderRoute: typeof OrganizerMarketingIndexRouteImport
      parentRoute: typeof OrganizerMarketingRoute
    }
    '/organizer/marketing/new': {
      id: '/organizer/marketing/new'
      path: '/new'
      fullPath: '/organizer/marketing/new'
      preLoaderRoute: typeof OrganizerMarketingNewRouteImport
      parentRoute: typeof OrganizerMarketingRoute
    }
    '/organizer/pos/': {
      id: '/organizer/pos/'
      path: '/pos'
      fullPath: '/organizer/pos/'
      preLoaderRoute: typeof OrganizerPosIndexRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/organizer/pos/cashier-sales': {
      id: '/organizer/pos/cashier-sales'
      path: '/pos/cashier-sales'
      fullPath: '/organizer/pos/cashier-sales'
      preLoaderRoute: typeof OrganizerPosCashierSalesRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/organizer/pos/cashiers': {
      id: '/organizer/pos/cashiers'
      path: '/pos/cashiers'
      fullPath: '/organizer/pos/cashiers'
      preLoaderRoute: typeof OrganizerPosCashiersRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/organizer/pos/closing': {
      id: '/organizer/pos/closing'
      path: '/pos/closing'
      fullPath: '/organizer/pos/closing'
      preLoaderRoute: typeof OrganizerPosClosingRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/organizer/pos/devices': {
      id: '/organizer/pos/devices'
      path: '/pos/devices'
      fullPath: '/organizer/pos/devices'
      preLoaderRoute: typeof OrganizerPosDevicesRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/organizer/pos/fiscal': {
      id: '/organizer/pos/fiscal'
      path: '/pos/fiscal'
      fullPath: '/organizer/pos/fiscal'
      preLoaderRoute: typeof OrganizerPosFiscalRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/organizer/pos/sales': {
      id: '/organizer/pos/sales'
      path: '/pos/sales'
      fullPath: '/organizer/pos/sales'
      preLoaderRoute: typeof OrganizerPosSalesRouteImport
      parentRoute: typeof OrganizerRoute
    }
    '/api/public/events/by-token': {
      id: '/api/public/events/by-token'
      path: '/api/public/events/by-token'
      fullPath: '/api/public/events/by-token'
      preLoaderRoute: typeof ApiPublicEventsByTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/reconcile': {
      id: '/api/public/payments/reconcile'
      path: '/api/public/payments/reconcile'
      fullPath: '/api/public/payments/reconcile'
      preLoaderRoute: typeof ApiPublicPaymentsReconcileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tickets/scan': {
      id: '/api/public/tickets/scan'
      path: '/api/public/tickets/scan'
      fullPath: '/api/public/tickets/scan'
      preLoaderRoute: typeof ApiPublicTicketsScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tickets/stats': {
      id: '/api/public/tickets/stats'
      path: '/api/public/tickets/stats'
      fullPath: '/api/public/tickets/stats'
      preLoaderRoute: typeof ApiPublicTicketsStatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/invoices/$orderId/pdf': {
      id: '/api/public/invoices/$orderId/pdf'
      path: '/api/public/invoices/$orderId/pdf'
      fullPath: '/api/public/invoices/$orderId/pdf'
      preLoaderRoute: typeof ApiPublicInvoicesOrderIdPdfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/gopay/webhook': {
      id: '/api/public/payments/gopay/webhook'
      path: '/api/public/payments/gopay/webhook'
      fullPath: '/api/public/payments/gopay/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsGopayWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/gpwebpay/return': {
      id: '/api/public/payments/gpwebpay/return'
      path: '/api/public/payments/gpwebpay/return'
      fullPath: '/api/public/payments/gpwebpay/return'
      preLoaderRoute: typeof ApiPublicPaymentsGpwebpayReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/tatrapayplus/return': {
      id: '/api/public/payments/tatrapayplus/return'
      path: '/api/public/payments/tatrapayplus/return'
      fullPath: '/api/public/payments/tatrapayplus/return'
      preLoaderRoute: typeof ApiPublicPaymentsTatrapayplusReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/data/categories/$categoryId/events/new': {
      id: '/admin/data/categories/$categoryId/events/new'
      path: '/$categoryId/events/new'
      fullPath: '/admin/data/categories/$categoryId/events/new'
      preLoaderRoute: typeof AdminDataCategoriesCategoryIdEventsNewRouteImport
      parentRoute: typeof AdminDataCategoriesRoute
    }
  }
}

interface AdminDataCategoriesRouteChildren {
  AdminDataCategoriesCategoryIdEventsNewRoute: typeof AdminDataCategoriesCategoryIdEventsNewRoute
}

const AdminDataCategoriesRouteChildren: AdminDataCategoriesRouteChildren = {
  AdminDataCategoriesCategoryIdEventsNewRoute:
    AdminDataCategoriesCategoryIdEventsNewRoute,
}

const AdminDataCategoriesRouteWithChildren =
  AdminDataCategoriesRoute._addFileChildren(AdminDataCategoriesRouteChildren)

interface AdminRouteChildren {
  AdminMarketingRoute: typeof AdminMarketingRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminDataCategoriesRoute: typeof AdminDataCategoriesRouteWithChildren
  AdminDataContentRoute: typeof AdminDataContentRoute
  AdminDataGroupsRoute: typeof AdminDataGroupsRoute
  AdminDataPerformersRoute: typeof AdminDataPerformersRoute
  AdminDataPriceCategoriesRoute: typeof AdminDataPriceCategoriesRoute
  AdminEticketoAccountingBankRoute: typeof AdminEticketoAccountingBankRoute
  AdminEticketoAccountingChecksRoute: typeof AdminEticketoAccountingChecksRoute
  AdminEticketoAccountingReportRoute: typeof AdminEticketoAccountingReportRoute
  AdminEticketoBalancesRoute: typeof AdminEticketoBalancesRoute
  AdminEticketoBillingRoute: typeof AdminEticketoBillingRoute
  AdminEticketoControlRoute: typeof AdminEticketoControlRoute
  AdminEticketoCostsRoute: typeof AdminEticketoCostsRoute
  AdminEticketoDevicesRoute: typeof AdminEticketoDevicesRoute
  AdminEticketoOrganizersRoute: typeof AdminEticketoOrganizersRoute
  AdminEticketoPaymentsRoute: typeof AdminEticketoPaymentsRoute
  AdminEticketoProtocolsRoute: typeof AdminEticketoProtocolsRoute
  AdminEticketoRefundTypesRoute: typeof AdminEticketoRefundTypesRoute
  AdminEticketoTicketsRoute: typeof AdminEticketoTicketsRoute
  AdminEventsCouponsRoute: typeof AdminEventsCouponsRoute
  AdminEventsDatesRoute: typeof AdminEventsDatesRoute
  AdminEventsEventsRoute: typeof AdminEventsEventsRoute
  AdminEventsVenueLayoutsRoute: typeof AdminEventsVenueLayoutsRoute
  AdminEventsVenuesRoute: typeof AdminEventsVenuesRoute
  AdminFinancePaymentsRoute: typeof AdminFinancePaymentsRoute
  AdminFinanceStatsRoute: typeof AdminFinanceStatsRoute
  AdminPosCashiersRoute: typeof AdminPosCashiersRoute
  AdminPosClosingsRoute: typeof AdminPosClosingsRoute
  AdminPosFiscalRoute: typeof AdminPosFiscalRoute
  AdminPosSalesRoute: typeof AdminPosSalesRoute
  AdminPosTerminalsRoute: typeof AdminPosTerminalsRoute
  AdminReportsSalesRoute: typeof AdminReportsSalesRoute
  AdminSalesCancellationsRoute: typeof AdminSalesCancellationsRoute
  AdminSalesNotesRoute: typeof AdminSalesNotesRoute
  AdminSalesSalesRoute: typeof AdminSalesSalesRoute
  AdminSystemEmailTemplatesRoute: typeof AdminSystemEmailTemplatesRoute
  AdminSystemHealthRoute: typeof AdminSystemHealthRoute
  AdminSystemPaymentsRoute: typeof AdminSystemPaymentsRoute
  AdminSystemUsersRoute: typeof AdminSystemUsersRoute
  AdminSystemWalletRoute: typeof AdminSystemWalletRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminMarketingRoute: AdminMarketingRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminDataCategoriesRoute: AdminDataCategoriesRouteWithChildren,
  AdminDataContentRoute: AdminDataContentRoute,
  AdminDataGroupsRoute: AdminDataGroupsRoute,
  AdminDataPerformersRoute: AdminDataPerformersRoute,
  AdminDataPriceCategoriesRoute: AdminDataPriceCategoriesRoute,
  AdminEticketoAccountingBankRoute: AdminEticketoAccountingBankRoute,
  AdminEticketoAccountingChecksRoute: AdminEticketoAccountingChecksRoute,
  AdminEticketoAccountingReportRoute: AdminEticketoAccountingReportRoute,
  AdminEticketoBalancesRoute: AdminEticketoBalancesRoute,
  AdminEticketoBillingRoute: AdminEticketoBillingRoute,
  AdminEticketoControlRoute: AdminEticketoControlRoute,
  AdminEticketoCostsRoute: AdminEticketoCostsRoute,
  AdminEticketoDevicesRoute: AdminEticketoDevicesRoute,
  AdminEticketoOrganizersRoute: AdminEticketoOrganizersRoute,
  AdminEticketoPaymentsRoute: AdminEticketoPaymentsRoute,
  AdminEticketoProtocolsRoute: AdminEticketoProtocolsRoute,
  AdminEticketoRefundTypesRoute: AdminEticketoRefundTypesRoute,
  AdminEticketoTicketsRoute: AdminEticketoTicketsRoute,
  AdminEventsCouponsRoute: AdminEventsCouponsRoute,
  AdminEventsDatesRoute: AdminEventsDatesRoute,
  AdminEventsEventsRoute: AdminEventsEventsRoute,
  AdminEventsVenueLayoutsRoute: AdminEventsVenueLayoutsRoute,
  AdminEventsVenuesRoute: AdminEventsVenuesRoute,
  AdminFinancePaymentsRoute: AdminFinancePaymentsRoute,
  AdminFinanceStatsRoute: AdminFinanceStatsRoute,
  AdminPosCashiersRoute: AdminPosCashiersRoute,
  AdminPosClosingsRoute: AdminPosClosingsRoute,
  AdminPosFiscalRoute: AdminPosFiscalRoute,
  AdminPosSalesRoute: AdminPosSalesRoute,
  AdminPosTerminalsRoute: AdminPosTerminalsRoute,
  AdminReportsSalesRoute: AdminReportsSalesRoute,
  AdminSalesCancellationsRoute: AdminSalesCancellationsRoute,
  AdminSalesNotesRoute: AdminSalesNotesRoute,
  AdminSalesSalesRoute: AdminSalesSalesRoute,
  AdminSystemEmailTemplatesRoute: AdminSystemEmailTemplatesRoute,
  AdminSystemHealthRoute: AdminSystemHealthRoute,
  AdminSystemPaymentsRoute: AdminSystemPaymentsRoute,
  AdminSystemUsersRoute: AdminSystemUsersRoute,
  AdminSystemWalletRoute: AdminSystemWalletRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface EventsRouteChildren {
  EventsIdRoute: typeof EventsIdRoute
}

const EventsRouteChildren: EventsRouteChildren = {
  EventsIdRoute: EventsIdRoute,
}

const EventsRouteWithChildren =
  EventsRoute._addFileChildren(EventsRouteChildren)

interface OrganizerEventsRouteChildren {
  OrganizerEventsNewRoute: typeof OrganizerEventsNewRoute
  OrganizerEventsIndexRoute: typeof OrganizerEventsIndexRoute
}

const OrganizerEventsRouteChildren: OrganizerEventsRouteChildren = {
  OrganizerEventsNewRoute: OrganizerEventsNewRoute,
  OrganizerEventsIndexRoute: OrganizerEventsIndexRoute,
}

const OrganizerEventsRouteWithChildren = OrganizerEventsRoute._addFileChildren(
  OrganizerEventsRouteChildren,
)

interface OrganizerMarketingRouteChildren {
  OrganizerMarketingNewRoute: typeof OrganizerMarketingNewRoute
  OrganizerMarketingIndexRoute: typeof OrganizerMarketingIndexRoute
}

const OrganizerMarketingRouteChildren: OrganizerMarketingRouteChildren = {
  OrganizerMarketingNewRoute: OrganizerMarketingNewRoute,
  OrganizerMarketingIndexRoute: OrganizerMarketingIndexRoute,
}

const OrganizerMarketingRouteWithChildren =
  OrganizerMarketingRoute._addFileChildren(OrganizerMarketingRouteChildren)

interface OrganizerRouteChildren {
  OrganizerEventsRoute: typeof OrganizerEventsRouteWithChildren
  OrganizerMarketingRoute: typeof OrganizerMarketingRouteWithChildren
  OrganizerIndexRoute: typeof OrganizerIndexRoute
  OrganizerPosCashierSalesRoute: typeof OrganizerPosCashierSalesRoute
  OrganizerPosCashiersRoute: typeof OrganizerPosCashiersRoute
  OrganizerPosClosingRoute: typeof OrganizerPosClosingRoute
  OrganizerPosDevicesRoute: typeof OrganizerPosDevicesRoute
  OrganizerPosFiscalRoute: typeof OrganizerPosFiscalRoute
  OrganizerPosSalesRoute: typeof OrganizerPosSalesRoute
  OrganizerPosIndexRoute: typeof OrganizerPosIndexRoute
}

const OrganizerRouteChildren: OrganizerRouteChildren = {
  OrganizerEventsRoute: OrganizerEventsRouteWithChildren,
  OrganizerMarketingRoute: OrganizerMarketingRouteWithChildren,
  OrganizerIndexRoute: OrganizerIndexRoute,
  OrganizerPosCashierSalesRoute: OrganizerPosCashierSalesRoute,
  OrganizerPosCashiersRoute: OrganizerPosCashiersRoute,
  OrganizerPosClosingRoute: OrganizerPosClosingRoute,
  OrganizerPosDevicesRoute: OrganizerPosDevicesRoute,
  OrganizerPosFiscalRoute: OrganizerPosFiscalRoute,
  OrganizerPosSalesRoute: OrganizerPosSalesRoute,
  OrganizerPosIndexRoute: OrganizerPosIndexRoute,
}

const OrganizerRouteWithChildren = OrganizerRoute._addFileChildren(
  OrganizerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRouteWithChildren,
  ArtistsRoute: ArtistsRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRouteWithChildren,
  LoginRoute: LoginRoute,
  MarketingRoute: MarketingRoute,
  OrganizerRoute: OrganizerRouteWithChildren,
  PartnersRoute: PartnersRoute,
  RegisterRoute: RegisterRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ScannerRoute: ScannerRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SupportRoute: SupportRoute,
  CheckoutOrderIdRoute: CheckoutOrderIdRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  PSlugRoute: PSlugRoute,
  ApiPublicSeedDemoRoute: ApiPublicSeedDemoRoute,
  CheckoutSuccessOrderIdRoute: CheckoutSuccessOrderIdRoute,
  ApiPublicEventsByTokenRoute: ApiPublicEventsByTokenRoute,
  ApiPublicPaymentsReconcileRoute: ApiPublicPaymentsReconcileRoute,
  ApiPublicTicketsScanRoute: ApiPublicTicketsScanRoute,
  ApiPublicTicketsStatsRoute: ApiPublicTicketsStatsRoute,
  ApiPublicInvoicesOrderIdPdfRoute: ApiPublicInvoicesOrderIdPdfRoute,
  ApiPublicPaymentsGopayWebhookRoute: ApiPublicPaymentsGopayWebhookRoute,
  ApiPublicPaymentsGpwebpayReturnRoute: ApiPublicPaymentsGpwebpayReturnRoute,
  ApiPublicPaymentsTatrapayplusReturnRoute:
    ApiPublicPaymentsTatrapayplusReturnRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
